import MagicReadiness from './MagicReadiness'
import { attributeFields } from './attributes'
import { spellTemplates } from './contentTemplates'
import { abilityLimits, abilityLimit, developmentStages, developmentLabel, branchParents, magicEfficiency, skillCatalog } from './creationRules'
import { functionalStates } from './functionalStates'
import { ArtworkPicker, Illustration } from './VisualElements'
import { itemPresets, abilityArtwork, artworkSource } from './visualMedia'
import AnatomyAtlas from './AnatomyAtlas'
import type { HitLocation } from './anatomyModel'
import { magicGroups, magicSchools, schoolById } from './magicCatalog'
import { useState } from 'react'
import { copyAbility, emptyAbility, isAbility } from './rpgSchema'
import type { AbilityDefinition, ActionInput, Campaign, LearnedAbility } from './rpgTypes'
import { bodyRegionDefs } from './characterBody'
import type { Actor, PlanResult } from './rpgEngine'
import { effectiveActor } from './rpgEngine'
import { Field, NumberField, TextField, TagsField, Check, ModifiersEditor } from './RpgControls'
export const mechanismLabels={stone:'Камень: тупое столкновение',impact:'Физическое попадание: удар, прокол или разрез',manual:'Ручное решение мастера',heal:'Лечение области',blood:'Восстановление крови',substitute:'Временное замещение крови',effect:'Изменение параметров'}
type Props={gameMode?:boolean;actor:Actor;characters:Actor[];campaign:Campaign;onChange:(a:Actor)=>void;onCampaign:(c:Campaign)=>{ok:boolean;message:string};onPreview:(abilityId:string,targetId:string,input:ActionInput)=>PlanResult;onRelease:(castId:string)=>PlanResult;onInterrupt:(castId:string)=>{ok:boolean;message:string};onPlan:(r:PlanResult)=>void}
export default function AbilitiesPanel({gameMode=false,actor,characters,campaign,onChange,onCampaign,onPreview,onRelease,onInterrupt,onPlan}:Props){
 const [form,setForm]=useState<AbilityDefinition|null>(null),[editing,setEditing]=useState<string|null>(null),[catalogId,setCatalogId]=useState<string|null>(null),[message,setMessage]=useState(''),[template,setTemplate]=useState(false)
 const [spellSchool,setSpellSchool]=useState((actor.profile.magic??[]).find(s=>s.state==='mastered')?.schoolId??'all')
 const [abilityId,setAbilityId]=useState(''),[targetId,setTargetId]=useState(actor.id)
 const target=characters.find(c=>c.id===targetId),areas=target?bodyRegionDefs(target.body):[]
 const [input,setInput]=useState<ActionInput>({region:'torso',distanceM:0,accessible:false,conditionsConfirmed:false,canSpeak:false,armorPath:'covered',gapConfirmed:false,criticalChance:0,dodgeChance:0,criticalContactFactor:1,manualLocal:0,manualSystemic:0,bleedingMlPerSecond:0,injury:'',note:''})
 const ability=actor.rpg.abilities.find(a=>a.id===abilityId)
 function learn(a:AbilityDefinition,templateId=''){if(actor.rpg.abilities.length>=200){setMessage('Список способностей заполнен.');return}const next:LearnedAbility={...copyAbility(a),id:crypto.randomUUID(),templateId,approved:false};onChange({...actor,rpg:{...actor.rpg,abilities:[...actor.rpg.abilities,next]}});setAbilityId(next.id);setMessage('Способность добавлена. Отметь утверждение перед применением.')}
 function submit(){if(!form||!isAbility(form)){setMessage('Проверь название, численные параметры и требования. Для камня нужны положительные масса, скорость и площадь контакта.');return}if(catalogId){const r=onCampaign({...campaign,abilities:campaign.abilities.map(t=>t.id===catalogId?{...copyAbility(form),id:t.id}:t)});setMessage(r.message);if(r.ok){setForm(null);setCatalogId(null)}return}if(template){if(campaign.abilities.length>=200){setMessage('Каталог заполнен.');return}const r=onCampaign({...campaign,abilities:[...campaign.abilities,{...copyAbility(form),id:crypto.randomUUID()}]});if(!r.ok){setMessage(r.message);return}}
 if(editing){onChange({...actor,rpg:{...actor.rpg,abilities:actor.rpg.abilities.map(a=>a.id===editing?{...copyAbility(form),id:a.id,templateId:a.templateId,approved:false}:a)}})}else learn(form)
 setForm(null);setEditing(null);setTemplate(false)
 }
 return <section><h3>{gameMode?'Применение способностей':'Способности и шаблоны магии'}</h3><div className="w6-category-gallery"><figure><Illustration fallback="weapons"/><figcaption>Физические воздействия</figcaption></figure><figure><Illustration fallback="artifact"/><figcaption>Магические эффекты</figcaption></figure><figure><Illustration fallback="supplies"/><figcaption>Лечение и жизнеобеспечение</figcaption></figure></div><p className="w6-copy">У каждого героя свой освоенный вариант. Изменение требует повторного утверждения; начатые применения сохраняют снимок прежних правил.</p><button className="w6-button w6-primary" type="button" onClick={()=>{setForm(emptyAbility());setEditing(null);setCatalogId(null);setTemplate(false)}}>Создать способность</button>
 {!gameMode&&<details className="w6-fieldset" open><summary>Шаблоны магии ({spellTemplates.length})</summary><Field label="Школа шаблонов"><select value={spellSchool} onChange={e=>setSpellSchool(e.currentTarget.value)}><option value="all">Все школы</option>{magicSchools.filter(s=>s.group!=='extended'&&s.id!=='limit').map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><div className="w6-spell-template-grid">{spellTemplates.filter(s=>spellSchool==='all'||s.schoolId===spellSchool).map(a=><article className="w6-spell-template" key={a.id}><small>{schoolById(a.schoolId??'')?.name} · {developmentLabel(a.minimumLevel??0)}</small><h4>{a.name}</h4><p>{abilityLimit(actor,a)||'Доступно для освоения'} · эффективность {Math.round(magicEfficiency(actor,a.schoolId??'',a.basisSchoolId)*100)}%</p><MagicReadiness actor={actor} ability={a} compact/><button className="w6-button" type="button" onClick={()=>{setForm(copyAbility(a));setEditing(null);setCatalogId(null)}}>Настроить шаблон</button><button className="w6-button w6-primary" type="button" disabled={!!abilityLimit(actor,a)} onClick={()=>learn(a,a.id)}>Добавить в лист</button></article>)}</div></details>}
 <details className="w6-fieldset"><summary>Общий каталог способностей ({campaign.abilities.length})</summary>{campaign.abilities.map(a=><article className="w6-entry" key={a.id}><img className="w6-entry-art w6-illustration" src={a.artwork&&a.artwork!=='auto'?artworkSource(a.artwork):abilityArtwork(a)} alt="" loading="lazy"/><h4>{a.name}</h4><p>{mechanismLabels[a.mechanism]}</p><div className="w6-buttons"><button className="w6-button" type="button" onClick={()=>learn(a,a.id)}>Освоить вариант</button><button className="w6-button" type="button" onClick={()=>{setForm(copyAbility(a));setEditing(null);setCatalogId(null);setTemplate(false)}}>Создать свой вариант</button><button className="w6-button" type="button" onClick={()=>{setForm(copyAbility(a));setEditing(null);setCatalogId(a.id);setTemplate(false)}}>Редактировать шаблон</button><button className="w6-button w6-danger" type="button" onClick={()=>{if(window.confirm('Удалить шаблон? Освоенные варианты сохранятся.'))setMessage(onCampaign({...campaign,abilities:campaign.abilities.filter(x=>x.id!==a.id)}).message)}}>Удалить шаблон</button></div></article>)}</details>
 {form&&<form className="w6-fieldset w6-form" onSubmit={e=>{e.preventDefault();submit()}}><h4>{catalogId?'Редактировать общий шаблон':editing?'Изменить освоенный вариант':'Новая способность'}</h4><Field label="Направление магии способности"><select aria-label="Направление магии способности" value={form.schoolId??''} onChange={e=>setForm({...form,schoolId:e.currentTarget.value})}><option value="">Не связано с направлением</option>{magicGroups.map(g=><optgroup key={g.id} label={g.label}>{magicSchools.filter(s=>s.group===g.id).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</optgroup>)}</select></Field><ArtworkPicker label="Изображение способности" value={form.artwork} presets={[...itemPresets,'stone']} onChange={artwork=>setForm({...form,artwork})}/><TextField label="Название способности" value={form.name} onChange={name=>setForm({...form,name})}/><Field label="Механизм и магические исключения"><textarea rows={4} maxLength={4000} value={form.description} onChange={e=>setForm({...form,description:e.currentTarget.value})}/></Field><Field label="Расчётная модель"><select value={form.mechanism} onChange={e=>setForm({...form,mechanism:e.currentTarget.value as AbilityDefinition['mechanism']})}>{Object.entries(mechanismLabels).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></Field>
 <div className="w6-attribute-grid"><NumberField label="Подготовка (с)" value={form.preparation} onChange={preparation=>setForm({...form,preparation})}/><NumberField label="Длительность после выпуска (с; 0 — до снятия)" value={form.duration} onChange={duration=>setForm({...form,duration})}/><NumberField label="Максимальная дальность (м)" value={form.rangeM} onChange={rangeM=>setForm({...form,rangeM})}/></div>
 {form.mechanism==='impact'&&<Field label="Тип физического воздействия"><select value={form.damageType??'blunt'} onChange={e=>setForm({...form,damageType:e.currentTarget.value as 'blunt'|'pierce'|'cut'})}><option value="blunt">Тупой удар</option><option value="pierce">Прокол</option><option value="cut">Разрез</option></select></Field>}
 <div className="w6-fieldset"><h4>Расходы</h4><div className="w6-attribute-grid">{(['mana','shadow','stamina'] as const).map(k=><NumberField key={k} label={{mana:'Мана при начале',shadow:'Тень при начале',stamina:'Выносливость при начале'}[k]} value={form.cost[k]} onChange={n=>setForm({...form,cost:{...form.cost,[k]:n}})}/>)}{(['mana','shadow','stamina'] as const).map(k=><NumberField key={'upkeep-'+k} label={{mana:'Мана поддержания (ед./с)',shadow:'Тень поддержания (ед./с)',stamina:'Выносливость поддержания (ед./с)'}[k]} value={form.upkeep[k]} onChange={n=>setForm({...form,upkeep:{...form.upkeep,[k]:n}})}/>)}</div><p className="w6-copy">Начало оплачивается после подтверждения предварительного результата. Прерывание не возвращает оплату. Поддержание используется у эффектов, восстановления и замещения крови.</p></div>
 <div className="w6-fieldset"><h4>Требования</h4><Check label="Нужно сознание" value={form.requiresAwake} onChange={requiresAwake=>setForm({...form,requiresAwake})}/><Field label="Руки"><select value={form.hands} onChange={e=>setForm({...form,hands:e.currentTarget.value as AbilityDefinition['hands']})}>{Object.entries({none:'Не требуются',any:'Любая одна',left:'Левая',right:'Правая',both:'Обе'}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Check label="Нужные руки должны быть свободны" value={form.freeHands} onChange={freeHands=>setForm({...form,freeHands})}/><Check label="Нужна возможность двигаться" value={form.movement} onChange={movement=>setForm({...form,movement})}/><Check label="Нужны работающие крылья" value={form.flight??false} onChange={flight=>setForm({...form,flight})}/><Check label="Нужно произнести слова" value={form.speech} onChange={speech=>setForm({...form,speech})}/><div className="w6-check-grid">{bodyRegionDefs(actor.body).map(r=><Check key={r.key} label={'Нужна работающая область: '+r.label} value={form.requiredParts.includes(r.key)} onChange={v=>setForm({...form,requiredParts:v?[...form.requiredParts,r.key]:form.requiredParts.filter(k=>k!==r.key)})}/>)}</div>{actor.body.anatomy&&<details className="w6-fieldset"><summary>Особые требования к внутренним структурам</summary><Field label="Нужные кости или органы"><select multiple size={8} value={form.requiredStructures??[]} onChange={e=>setForm({...form,requiredStructures:Array.from(e.currentTarget.selectedOptions,o=>o.value)})}>{actor.body.anatomy.structures.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><p className="w6-copy">Выбирай несколько с Ctrl. При нулевой целостности или блокирующей травме хотя бы одной выбранной структуры действие недоступно.</p></details>}<TagsField label="Метки необходимых экипированных предметов" value={form.requiredTags} onChange={requiredTags=>setForm({...form,requiredTags})}/><TextField label="Особое условие" max={1000} value={form.condition} onChange={condition=>setForm({...form,condition})}/></div>
 {['stone','impact'].includes(form.mechanism)&&<div className="w6-attribute-grid"><NumberField label="Масса камня (кг)" value={form.massKg} onChange={massKg=>setForm({...form,massKg})}/><NumberField label="Скорость в момент столкновения (м/с)" value={form.speedMs} onChange={speedMs=>setForm({...form,speedMs})}/><NumberField label="Площадь контакта (см²)" value={form.contactCm2} onChange={contactCm2=>setForm({...form,contactCm2})}/></div>}
 {form.mechanism==='heal'&&<><NumberField label="Локальное восстановление (HP)" value={form.healAmount} onChange={healAmount=>setForm({...form,healAmount})}/><Check label="Остановить кровь выбранной области" value={form.stopBleeding} onChange={stopBleeding=>setForm({...form,stopBleeding})}/><TagsField label="Названия снимаемых травм" value={form.cureLabels} onChange={cureLabels=>setForm({...form,cureLabels})}/></>}
 {form.mechanism==='blood'&&<NumberField label="Создание настоящей крови (мл/с)" value={form.bloodMlPerSecond} onChange={bloodMlPerSecond=>setForm({...form,bloodMlPerSecond})}/>}
 {form.mechanism==='substitute'&&<NumberField label="Эквивалент временно заменяемой крови (мл)" value={form.substituteMl} onChange={substituteMl=>setForm({...form,substituteMl})}/>}
 {['effect','blood','substitute'].includes(form.mechanism)&&<><ModifiersEditor value={form.modifiers} onChange={modifiers=>setForm({...form,modifiers})}/><NumberField label="Сила для сравнения одинаковых эффектов" value={form.strength} onChange={strength=>setForm({...form,strength})}/><TextField label="Ключ группы одинаковых эффектов" value={form.stackKey} onChange={stackKey=>setForm({...form,stackKey})}/><Field label="Взаимодействие в группе"><select value={form.stacking} onChange={e=>setForm({...form,stacking:e.currentTarget.value as AbilityDefinition['stacking']})}><option value="strongest">Действует наиболее сильный</option><option value="add">Складываются</option><option value="refresh">Новый заменяет прежний</option></select></Field></>}
 <div className="w6-fieldset"><h4>Развитие и ограничения</h4><MagicReadiness actor={actor} ability={form}/>{schoolById(form.schoolId??'')?.group==='extended'&&!branchParents[form.schoolId??'']&&<Field label="Школа-основа техники"><select aria-label="Школа-основа техники" value={form.basisSchoolId??''} onChange={e=>setForm({...form,basisSchoolId:e.currentTarget.value||undefined})}><option value="">Выбери основу</option>{magicSchools.filter(s=>s.group!=='extended'&&s.id!=='limit').map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field>}<p className="w6-copy">Для магии сейчас: сила до {abilityLimits(actor.profile).power}, дальность до {abilityLimits(actor.profile).range} м, длительность до {abilityLimits(actor.profile).duration} с.</p><Field label="Базовый навык способности"><select value={form.skillId??(form.schoolId?'spellcraft':'melee')} onChange={e=>setForm({...form,skillId:e.currentTarget.value})}>{skillCatalog.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><div className="w6-attribute-grid"><NumberField label="Собственное мастерство (0–100)" max={100} value={form.mastery??20} onChange={mastery=>setForm({...form,mastery})}/><Field label="Минимальные ранг и ступень"><select aria-label="Минимальные ранг и ступень" value={form.minimumLevel??0} onChange={e=>setForm({...form,minimumLevel:Number(e.currentTarget.value)})}>{!developmentStages.some(s=>s.value===(form.minimumLevel??0))&&<option value={form.minimumLevel}>{developmentLabel(form.minimumLevel??0)} · текущий порог</option>}{developmentStages.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></Field></div><details><summary>Требуемые атрибуты</summary><div className="w6-attribute-grid">{attributeFields.map(a=><NumberField key={a.key} label={a.label} value={form.attributeRequirements?.[a.key]??0} onChange={n=>setForm({...form,attributeRequirements:{...form.attributeRequirements,[a.key]:n}})}/>)}</div></details><details><summary>Функциональные эффекты</summary><div className="w6-check-grid">{functionalStates.map(s=><Check key={s.id} label={s.name} value={(form.statusEffects??[]).includes(s.id)} onChange={checked=>setForm({...form,statusEffects:checked?[...(form.statusEffects??[]),s.id]:(form.statusEffects??[]).filter(x=>x!==s.id)})}/>)}</div></details></div>
 <Check label="Также добавить новый шаблон в общий каталог" value={template} onChange={setTemplate}/><div className="w6-buttons"><button className="w6-button w6-primary" type="submit">Применить способность</button><button className="w6-button" type="button" onClick={()=>setForm(null)}>Отмена</button></div></form>}
 <div className="w6-entry-list">{actor.rpg.abilities.map(a=><article className="w6-entry" key={a.id}><img className="w6-entry-art w6-illustration" src={a.artwork&&a.artwork!=='auto'?artworkSource(a.artwork):abilityArtwork(a)} alt="" loading="lazy"/><h4>{a.name}</h4>{a.schoolId&&<p className="w6-copy">Школа: {schoolById(a.schoolId)?.name}</p>}<p className="w6-prose">{a.description}</p><MagicReadiness actor={actor} ability={a} compact/><p>{mechanismLabels[a.mechanism]} · Подготовка {a.preparation} с · Дальность {a.rangeM} м</p><Check label={'Утверждена мастером: '+a.name} value={a.approved} onChange={approved=>onChange({...actor,rpg:{...actor.rpg,abilities:actor.rpg.abilities.map(x=>x.id===a.id?{...x,approved}:x)}})}/><div className="w6-buttons"><button className="w6-button" type="button" onClick={()=>setAbilityId(a.id)}>Выбрать для применения</button><button className="w6-button" type="button" onClick={()=>{setEditing(a.id);setForm(copyAbility(a));setCatalogId(null);setTemplate(false)}}>Изменить параметры</button><button className="w6-button w6-danger" type="button" onClick={()=>{if(window.confirm('Удалить освоенную способность? История сохранится.'))onChange({...actor,rpg:{...actor.rpg,abilities:actor.rpg.abilities.filter(x=>x.id!==a.id)}})}}>Удалить</button></div></article>)}</div>
 {gameMode&&<><form className="w6-fieldset w6-form" onSubmit={e=>{e.preventDefault();onPlan(onPreview(abilityId,targetId,input))}}><h4>Применение к цели</h4><div className="w6-attribute-grid"><Field label="Способность для действия"><select required value={abilityId} onChange={e=>setAbilityId(e.currentTarget.value)}><option value="">Выбери способность</option>{actor.rpg.abilities.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><Field label="Персонаж-цель"><select value={targetId} onChange={e=>{setTargetId(e.currentTarget.value);setInput({...input,accessible:false,gapConfirmed:false,structureId:undefined})}}>{characters.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Область цели"><select value={input.region} onChange={e=>setInput({...input,region:e.currentTarget.value,structureId:undefined})}><option value="">Выбери область</option>{areas.map(r=><option value={r.key} key={r.key}>{r.label}</option>)}</select></Field><NumberField label="Фактическая дистанция (м)" value={input.distanceM} onChange={distanceM=>setInput({...input,distanceM})}/></div>
 <Check label="Мастер подтвердил доступность цели и отсутствие препятствий" value={input.accessible} onChange={accessible=>setInput({...input,accessible})}/>{ability?.condition&&<Check label={'Подтверждено условие: '+ability.condition} value={input.conditionsConfirmed} onChange={conditionsConfirmed=>setInput({...input,conditionsConfirmed})}/>} {ability?.speech&&<Check label="Применяющий может произнести слова" value={input.canSpeak} onChange={canSpeak=>setInput({...input,canSpeak})}/>}
 {ability&&['stone','impact','manual'].includes(ability.mechanism)&&<><div className="w6-attribute-grid"><NumberField label="Шанс крита этого действия (%)" max={100} value={input.criticalChance} onChange={criticalChance=>setInput({...input,criticalChance})}/><NumberField label="Шанс уворота цели (%)" max={100} value={input.dodgeChance} onChange={dodgeChance=>setInput({...input,dodgeChance})}/><NumberField label="Коэффициент удачного контакта при крите" value={input.criticalContactFactor} onChange={criticalContactFactor=>setInput({...input,criticalContactFactor})}/></div><p className="w6-copy">Шансы задаются для текущих условий. Значения из листа можно использовать кнопкой ниже; уворот и крит — единственные случайные проверки.</p><button className="w6-button" type="button" onClick={()=>setInput({...input,criticalChance:Number(effectiveActor(actor,campaign.seconds).statistics.criticalChance)||0,dodgeChance:target?Number(effectiveActor(target,campaign.seconds).statistics.dodgeChance)||0:0})}>Взять базовые шансы из листов</button>
 {['stone','impact'].includes(ability.mechanism)&&<><Field label="Путь попадания"><select value={input.armorPath} onChange={e=>setInput({...input,armorPath:e.currentTarget.value as ActionInput['armorPath']})}><option value="covered">Через покрывающие слои</option><option value="gap">В открытый зазор</option></select></Field>{input.armorPath==='gap'&&<Check label="Мастер подтвердил открытый зазор" value={input.gapConfirmed} onChange={gapConfirmed=>setInput({...input,gapConfirmed})}/>}</>}
 <div className="w6-attribute-grid">{ability.mechanism==='manual'&&<NumberField label="Локальный урон по решению мастера" value={input.manualLocal} onChange={manualLocal=>setInput({...input,manualLocal})}/>}<NumberField label="Кровотечение области после попадания (мл/с)" value={input.bleedingMlPerSecond} onChange={bleedingMlPerSecond=>setInput({...input,bleedingMlPerSecond})}/><TextField label="Отдельная травма, если определена мастером" value={input.injury} onChange={injury=>setInput({...input,injury})}/></div></>}
 {target?.body.anatomy&&ability?.mechanism==='heal'&&<Field label="Что лечить в выбранной области"><select value={input.structureId??''} onChange={e=>setInput({...input,structureId:e.currentTarget.value})}><option value="">Локальное HP области</option>{target.body.anatomy.structures.filter(s=>s.region===input.region).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field>}
 {target?.body.anatomy&&ability&&['stone','impact'].includes(ability.mechanism)&&<div className="w6-fieldset"><h4>Точка и внутренний путь попадания</h4><p className="w6-copy">Выбери область на фигуре и точку внутри неё. По умолчанию используется центр области. Внутренний путь использует энергию после брони; камень всегда даёт тупой удар.</p><AnatomyAtlas body={target.body} selectedRegion={input.region} point={input.hit} onSelectRegion={region=>setInput({...input,region,skipAnatomy:false,hit:{x:.5,y:.5,approach:'front',mechanism:ability.mechanism==='stone'?'blunt':ability.damageType??'blunt',angleX:0,angleY:0}})} onPoint={(hit:HitLocation)=>setInput({...input,hit,skipAnatomy:false})}/><button className="w6-button" type="button" onClick={()=>setInput({...input,hit:undefined,skipAnatomy:!input.skipAnatomy})}>{input.skipAnatomy?'Включить внутренний расчёт':'Только локальный HP, без внутреннего расчёта'}</button>{input.hit&&<div className="w6-attribute-grid"><NumberField label="Точка X внутри области (0–1)" max={1} value={input.hit.x} onChange={x=>setInput({...input,hit:{...input.hit!,x}})}/><NumberField label="Точка Y внутри области (0–1)" max={1} value={input.hit.y} onChange={y=>setInput({...input,hit:{...input.hit!,y}})}/><Field label="Направление попадания"><select value={input.hit.approach} onChange={e=>setInput({...input,hit:{...input.hit!,approach:e.currentTarget.value as 'front'|'back'}})}><option value="front">Спереди</option><option value="back">Сзади</option></select></Field><label className="w6-field"><span>Наклон X (−1…1)</span><input type="number" step="0.1" min={-1} max={1} value={input.hit.angleX} onChange={e=>setInput({...input,hit:{...input.hit!,angleX:Number(e.currentTarget.value)}})}/></label><label className="w6-field"><span>Наклон Y (−1…1)</span><input type="number" step="0.1" min={-1} max={1} value={input.hit.angleY} onChange={e=>setInput({...input,hit:{...input.hit!,angleY:Number(e.currentTarget.value)}})}/></label></div>}</div>}
 <TextField label="Основание и поправки мастера" max={1000} value={input.note} onChange={note=>setInput({...input,note})}/><button className="w6-button w6-primary" type="submit" disabled={!ability}>Рассчитать предварительный результат</button></form>
 <h4>Начатые применения</h4>{actor.rpg.casts.filter(c=>['preparing','ready','maintaining'].includes(c.status)).map(c=><article className="w6-entry" key={c.id}><h4>{c.ability.name}</h4><p>{{preparing:'Подготовка',ready:'Готова к выпуску',maintaining:'Поддерживается',ended:'Завершена',interrupted:'Прервана'}[c.status]} · Цель: {characters.find(x=>x.id===c.targetId)?.name||'Отсутствует'} · Готовность: {c.readyAt} с</p><div className="w6-buttons">{c.status==='ready'&&<button className="w6-button w6-primary" type="button" onClick={()=>onPlan(onRelease(c.id))}>Рассчитать выпуск</button>}<button className="w6-button w6-danger" type="button" onClick={()=>setMessage(onInterrupt(c.id).message)}>Прервать без возврата расхода</button></div></article>)}
 </>}<details className="w6-fieldset"><summary>История действий ({actor.rpg.logs.length})</summary>{actor.rpg.logs.slice().reverse().map(l=><article className="w6-entry" key={l.id}><h4>{l.seconds} с · {l.text}</h4><p className="w6-prose">{l.details}</p></article>)}</details><p role="status" className="w6-notice">{message}</p></section>
}
