import { useEffect, useRef, useState } from 'react'
import * as THREE from 'three'
import { OrbitControls } from 'three/addons/controls/OrbitControls.js'
import type { ReadyCharacterDraft } from './characterModel'
import type { ItemDefinition } from './rpgTypes'
import { buildArtifact, buildCharacter, disposeObject } from './viewportGeometry'
import AnatomySilhouette from './AnatomySilhouette'

type View={scene:THREE.Scene;renderer:THREE.WebGLRenderer;camera:THREE.PerspectiveCamera;controls:OrbitControls;root:THREE.Group|null;fit:()=>void;spin:boolean;lost:boolean}
export default function BodyViewport({actor,item,onRegion}:{actor?:ReadyCharacterDraft;item?:ItemDefinition;onRegion?:(region:string)=>void}){
 const host=useRef<HTMLDivElement>(null),view=useRef<View|null>(null),callback=useRef(onRegion),actorRef=useRef(actor),[error,setError]=useState(''),[selected,setSelected]=useState(''),[epoch,setEpoch]=useState(0),[spin,setSpin]=useState(false)
 const isItem=!!item
 useEffect(()=>{callback.current=onRegion;actorRef.current=actor},[actor,onRegion])
 useEffect(()=>{
  const target=host.current;if(!target)return
  let renderer:THREE.WebGLRenderer
  try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'default',alpha:false})}catch{setError('Браузер не предоставил WebGL. Можно продолжать редактирование и пользоваться 2D атласом.');return}
  const scene=new THREE.Scene();scene.background=new THREE.Color('#111d25');scene.fog=new THREE.Fog('#111d25',7,14)
  renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;target.appendChild(renderer.domElement)
  const camera=new THREE.PerspectiveCamera(32,1,.01,50),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.09;controls.minDistance=.4;controls.maxDistance=10;controls.maxPolarAngle=Math.PI*.89;controls.enablePan=true
  scene.add(new THREE.HemisphereLight('#c4dfef','#263039',2.1));const key=new THREE.DirectionalLight('#ffe4c4',3);key.position.set(-3,5,4);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-2;key.shadow.camera.right=2;key.shadow.camera.top=3;key.shadow.camera.bottom=-1;key.shadow.normalBias=.02;scene.add(key);const rim=new THREE.DirectionalLight('#90c5df',2.4);rim.position.set(3,2,-3);scene.add(rim);const fill=new THREE.DirectionalLight('#c9d5e5',.65);fill.position.set(2,2,4);scene.add(fill)
  const platform=new THREE.Mesh(new THREE.CylinderGeometry(.73,.78,.065,72),new THREE.MeshStandardMaterial({color:'#263b49',metalness:.42,roughness:.5}));platform.position.y=-.035;platform.receiveShadow=true;scene.add(platform);const grid=new THREE.GridHelper(6,30,'#364650','#25333d');grid.position.y=-.069;scene.add(grid)
  const state:View={scene,renderer,camera,controls,root:null,spin:false,lost:false,fit:()=>{const box=state.root?new THREE.Box3().setFromObject(state.root):new THREE.Box3(v(-.5,0,-.5),v(.5,2,.5)),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),radius=Math.max(size.y,size.x/(camera.aspect||1),size.z)*.5,dist=Math.max(.8,radius/Math.tan(THREE.MathUtils.degToRad(camera.fov/2))*1.2);controls.target.copy(center);camera.position.copy(center.clone().add(new THREE.Vector3(dist*.24,dist*.1,dist)));controls.update()}}
  function v(x:number,y:number,z:number){return new THREE.Vector3(x,y,z)}
  view.current=state;setError('')
  const resize=()=>{const width=Math.max(1,target.clientWidth),height=Math.max(1,target.clientHeight);renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix()};resize();const observer=new ResizeObserver(resize);observer.observe(target)
  const lost=(event:Event)=>{event.preventDefault();state.lost=true;setError('3D контекст потерян. Параметры сохранены в черновике; нажми «Восстановить 3D».')};renderer.domElement.addEventListener('webglcontextlost',lost)
  let startX=0,startY=0;const down=(e:PointerEvent)=>{startX=e.clientX;startY=e.clientY},up=(e:PointerEvent)=>{if(!state.root||Math.hypot(e.clientX-startX,e.clientY-startY)>5)return;const rect=renderer.domElement.getBoundingClientRect(),pointer=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(state.root.children,true).find(h=>h.object.userData.region);if(hit){const region=(hit.object.userData.faceRegions?.[hit.faceIndex??0]??hit.object.userData.region) as string;setSelected(actorRef.current?.body.parts[region]?.label??region);callback.current?.(region)}};renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointerup',up)
  let frame=0,last=0;const render=(time:number)=>{frame=requestAnimationFrame(render);if(state.lost||document.hidden||target.offsetParent===null||time-last<32)return;last=time;if(state.spin&&state.root)state.root.rotation.y+=.009;controls.update();try{renderer.render(scene,camera)}catch(e){state.lost=true;setError('Ошибка 3D: '+(e instanceof Error?e.message:'не удалось отрисовать модель'))}};frame=requestAnimationFrame(render)
  return ()=>{cancelAnimationFrame(frame);observer.disconnect();controls.dispose();renderer.domElement.removeEventListener('webglcontextlost',lost);renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('pointerup',up);disposeObject(scene);grid.geometry.dispose();(grid.material as THREE.Material).dispose();renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();if(view.current===state)view.current=null}
 },[isItem,epoch])
 useEffect(()=>{const state=view.current;if(!state)return;const timer=window.setTimeout(()=>{try{const rotation=state.root?.rotation.y??0,old=state.root,next=item?buildArtifact(item):actor?buildCharacter(actor):new THREE.Group();if(item){const box=new THREE.Box3().setFromObject(next);next.position.y=-box.min.y}next.rotation.y=rotation;state.scene.add(next);state.root=next;if(old){const previous=new THREE.Box3().setFromObject(old),current=new THREE.Box3().setFromObject(next),oldSize=previous.getSize(new THREE.Vector3()),newSize=current.getSize(new THREE.Vector3()),extent=(s:THREE.Vector3)=>Math.max(s.y,s.x/state.camera.aspect,s.z),ratio=extent(newSize)/Math.max(.001,extent(oldSize)),offset=state.camera.position.clone().sub(state.controls.target),center=current.getCenter(new THREE.Vector3());state.controls.target.copy(center);state.camera.position.copy(center.add(offset.multiplyScalar(ratio)));state.controls.update();state.scene.remove(old);disposeObject(old)}else state.fit();setError('')}catch(e){setError('Модель не построена: '+(e instanceof Error?e.message:'проверь параметры'))}},50);return ()=>window.clearTimeout(timer)},[actor,item,epoch])
 useEffect(()=>{if(view.current)view.current.spin=spin},[spin,epoch])
 function cameraView(back:boolean){const state=view.current;if(!state)return;state.fit();const delta=state.camera.position.clone().sub(state.controls.target);state.camera.position.copy(state.controls.target.clone().add(new THREE.Vector3(0,delta.y,(back?-1:1)*delta.length())));state.controls.update()}
 return <div className="w6-viewport-wrap"><div className="w6-view-controls"><button type="button" className="w6-button" onClick={()=>cameraView(false)}>Спереди</button><button type="button" className="w6-button" onClick={()=>cameraView(true)}>Сзади</button><button type="button" className="w6-button" onClick={()=>view.current?.fit()}>Вписать модель</button><button type="button" className={'w6-button'+(spin?' w6-active':'')} aria-pressed={spin} onClick={()=>setSpin(!spin)}>Вращение</button></div><div ref={host} className={'w6-viewport'+(item?' w6-item-viewport':'')} role="img" aria-label={item?'3D модель предмета':'Вращаемая 3D модель тела'} />{error&&<div className="w6-3d-fallback"><p className="w6-error" role="status">{error}</p>{actor&&<svg viewBox="0 0 300 600" role="img" aria-label="2D резервная проекция тела"><AnatomySilhouette form={actor.body.anatomy?.form??'humanoid'} parts={Object.keys(actor.body.parts)}/></svg>}<button type="button" className="w6-button" onClick={()=>setEpoch(epoch+1)}>Восстановить 3D</button></div>}<div className="w6-viewport-caption"><span>{selected||'3D · '+(item?'Предмет':'Тело и снаряжение')}</span><span>Потяни для вращения · колесо для масштаба</span></div></div>
}
