import { fail,text,choice,id,now,character,integer,publicUser } from './validation.mjs'
export function communityRoutes(app,{db,auth,io}){
 const changed=area=>io.to('public').emit('communityChanged',{area})
 app.get('/api/characters',auth.middleware,async(req,res)=>res.json(await db.all('SELECT id,name,revision,updated_at FROM characters WHERE owner_id=? ORDER BY updated_at DESC',[req.user.id])))
 app.get('/api/characters/:id',auth.middleware,async(req,res)=>{const row=await db.get('SELECT * FROM characters WHERE id=? AND owner_id=?',[req.params.id,req.user.id]);if(!row)fail(404,'Герой не найден в твоём аккаунте.');res.json({character:JSON.parse(row.data_json),revision:row.revision})})
 app.put('/api/characters/:id',auth.middleware,async(req,res)=>{const data=character(req.body.character);if(data.id!==req.params.id)fail(400,'ID листа и адреса не совпадают.');const revision=integer(req.body.revision,-1);let nextRevision=0;await db.transaction(async tx=>{const row=await tx.get('SELECT * FROM characters WHERE id=?'+tx.lock,[data.id]);if(row){if(row.owner_id!==req.user.id)fail(403,'Этот ID уже принадлежит другому аккаунту.');if(row.revision!==revision)fail(409,'Герой изменён на другом устройстве. Сначала загрузи свежую версию.');const result=await tx.run('UPDATE characters SET name=?,data_json=?,revision=revision+1,updated_at=? WHERE id=? AND revision=?',[data.name,JSON.stringify(data),now(),data.id,revision]);if(Number(result.changes)!==1)fail(409,'Конфликт сохранения.');nextRevision=revision+1}else{if(revision!==-1)fail(409,'Герой удалён на другом устройстве.');const count=await tx.get('SELECT COUNT(*) AS n FROM characters WHERE owner_id=?',[req.user.id]);if(Number(count.n)>=200)fail(409,'В аккаунте уже 200 героев.');await tx.run('INSERT INTO characters(id,owner_id,name,data_json,updated_at) VALUES(?,?,?,?,?)',[data.id,req.user.id,data.name,JSON.stringify(data),now()])}});res.json({revision:nextRevision})})
 app.delete('/api/characters/:id',auth.middleware,async(req,res)=>{await db.run('DELETE FROM characters WHERE id=? AND owner_id=?',[req.params.id,req.user.id]);res.json({ok:true})})
 app.get('/api/publications/:kind',async(req,res)=>{const kind=choice(req.params.kind,['news','stories']),offset=Math.max(0,Math.min(10000,Number(req.query.offset)||0)),rows=await db.all('SELECT p.*,u.display_name AS author FROM publications p JOIN users u ON u.id=p.author_id WHERE p.kind=? ORDER BY p.created_at DESC,p.id LIMIT 21 OFFSET ?',[kind,offset]);res.json({items:rows.slice(0,20),hasMore:rows.length>20})})
 app.post('/api/publications/:kind',auth.middleware,async(req,res)=>{const kind=choice(req.params.kind,['news','stories']);if(kind==='news')auth.moderator(req.user);const publication={id:id(),title:text(req.body.title,120),body:text(req.body.body,20000),created_at:now()};await db.run('INSERT INTO publications(id,author_id,kind,title,body,created_at,updated_at) VALUES(?,?,?,?,?,?,?)',[publication.id,req.user.id,kind,publication.title,publication.body,publication.created_at,publication.created_at]);changed(kind);res.status(201).json(publication)})
 app.delete('/api/publications/:kind/:id',auth.middleware,async(req,res)=>{const row=await db.get('SELECT * FROM publications WHERE id=? AND kind=?',[req.params.id,choice(req.params.kind,['news','stories'])]);if(!row)fail(404,'Публикация не найдена.');if(row.author_id!==req.user.id||row.kind==='news')auth.moderator(req.user);await db.run('DELETE FROM publications WHERE id=?',[row.id]);changed(row.kind);res.json({ok:true})})
 app.get('/api/support',auth.middleware,async(req,res)=>{if(['ADMIN','OWNER'].includes(req.user.role))auth.moderator(req.user);const rows=await db.all('SELECT t.*,u.display_name AS author FROM tickets t JOIN users u ON u.id=t.author_id'+(['ADMIN','OWNER'].includes(req.user.role)?'':' WHERE t.author_id=?')+' ORDER BY t.updated_at DESC LIMIT 100',['ADMIN','OWNER'].includes(req.user.role)?[]:[req.user.id]);res.json(rows)})
 app.post('/api/support',auth.middleware,async(req,res)=>{const ticket={id:id(),title:text(req.body.title,120),body:text(req.body.body),created_at:now()};await db.run('INSERT INTO tickets(id,author_id,title,body,created_at,updated_at) VALUES(?,?,?,?,?,?)',[ticket.id,req.user.id,ticket.title,ticket.body,ticket.created_at,ticket.created_at]);res.status(201).json(ticket)})
 async function ticketAccess(ticketId,user){const ticket=await db.get('SELECT t.*,u.display_name AS author FROM tickets t JOIN users u ON u.id=t.author_id WHERE t.id=?',[ticketId]);if(!ticket)fail(404,'Обращение не найдено.');if(ticket.author_id!==user.id)auth.moderator(user);return ticket}
 app.get('/api/support/:id',auth.middleware,async(req,res)=>{const ticket=await ticketAccess(req.params.id,req.user),replies=await db.all('SELECT r.*,u.display_name AS author FROM ticket_replies r JOIN users u ON u.id=r.author_id WHERE r.ticket_id=? ORDER BY r.created_at LIMIT 500',[ticket.id]);res.json({ticket,replies})})
 app.post('/api/support/:id/replies',auth.middleware,async(req,res)=>{const ticket=await ticketAccess(req.params.id,req.user);if(ticket.status==='closed')fail(409,'Обращение закрыто.');await db.run('INSERT INTO ticket_replies(id,ticket_id,author_id,body,created_at) VALUES(?,?,?,?,?)',[id(),ticket.id,req.user.id,text(req.body.body),now()]);await db.run('UPDATE tickets SET updated_at=? WHERE id=?',[now(),ticket.id]);res.status(201).json({ok:true})})
 app.patch('/api/support/:id',auth.middleware,async(req,res)=>{const ticket=await ticketAccess(req.params.id,req.user);auth.moderator(req.user);await db.run('UPDATE tickets SET status=?,updated_at=? WHERE id=?',[choice(req.body.status,['open','working','closed']),now(),ticket.id]);res.json({ok:true})})
 app.get('/api/admin/users',auth.middleware,async(req,res)=>{auth.moderator(req.user);res.json((await db.all('SELECT id,display_name,email,role,disabled,created_at FROM users ORDER BY created_at DESC LIMIT 500')).map(u=>({...publicUser(u),email:u.email,createdAt:u.created_at})))})
 app.patch('/api/admin/users/:id',auth.middleware,async(req,res)=>{auth.moderator(req.user);const target=await db.get('SELECT * FROM users WHERE id=?',[req.params.id]);if(!target)fail(404,'Аккаунт не найден.');if(target.role==='OWNER'||target.id===req.user.id)fail(403,'Нельзя менять владельца или свой доступ через эту форму.');if(target.role==='ADMIN'&&req.user.role!=='OWNER')fail(403,'Администратора изменяет владелец.');let role=target.role;if(req.body.role!==undefined){if(req.user.role!=='OWNER')fail(403,'Назначать роли может владелец.');role=choice(req.body.role,['PLAYER','GM','WORLD_EDITOR','ADMIN'])}const disabled=req.body.disabled===undefined?target.disabled:req.body.disabled===true?1:0;await db.run('UPDATE users SET role=?,disabled=? WHERE id=?',[role,disabled,target.id]);await db.run('INSERT INTO audit(id,actor_id,action,target_id,created_at) VALUES(?,?,?,?,?)',[id(),req.user.id,'change-user',target.id,now()]);io.in('user:'+target.id).disconnectSockets(true);res.json({ok:true})})
 app.get('/api/admin/audit',auth.middleware,async(req,res)=>{auth.moderator(req.user);res.json(await db.all('SELECT a.*,u.display_name AS actor FROM audit a JOIN users u ON u.id=a.actor_id ORDER BY a.created_at DESC LIMIT 200'))})
}
