import { fail,text,choice,id,now } from './validation.mjs'
export const categories=[{id:'general',name:'Общие обсуждения'},{id:'lore',name:'Лор и мир'},{id:'rules',name:'Правила и механика'},{id:'ideas',name:'Идеи и предложения'}]
export function forumRoutes(app,{db,auth,io}){
 const notify=()=>io.to('public').emit('communityChanged',{area:'forum'})
 app.get('/api/forum/categories',(req,res)=>res.json(categories))
 app.get('/api/forum/topics',async(req,res)=>{const q=String(req.query.q||'').slice(0,120).toLowerCase(),cat=String(req.query.category||''),offset=Math.max(0,Math.min(10000,Number(req.query.offset)||0)),args=['%'+q+'%','%'+q+'%'];let filter='t.deleted=0 AND (LOWER(t.title) LIKE ? OR LOWER(t.body) LIKE ?)';if(cat){choice(cat,categories.map(c=>c.id));filter+=' AND t.category=?';args.push(cat)}const rows=await db.all(`SELECT t.*,u.display_name AS author,(SELECT COUNT(*) FROM replies r WHERE r.topic_id=t.id AND r.deleted=0) AS replies FROM topics t JOIN users u ON u.id=t.author_id WHERE ${filter} ORDER BY t.pinned DESC,t.updated_at DESC,t.id DESC LIMIT 21 OFFSET ?`,[...args,offset]);res.json({items:rows.slice(0,20),hasMore:rows.length>20})})
 app.post('/api/forum/topics',auth.middleware,async(req,res)=>{const topic={id:id(),author_id:req.user.id,title:text(req.body.title,120),body:text(req.body.body),category:choice(req.body.category,categories.map(c=>c.id)),created_at:now()};await db.run('INSERT INTO topics(id,author_id,title,body,category,created_at,updated_at) VALUES(?,?,?,?,?,?,?)',[topic.id,topic.author_id,topic.title,topic.body,topic.category,topic.created_at,topic.created_at]);notify();res.status(201).json(topic)})
 app.get('/api/forum/topics/:id',async(req,res)=>{const topic=await db.get('SELECT t.*,u.display_name AS author FROM topics t JOIN users u ON u.id=t.author_id WHERE t.id=? AND t.deleted=0',[req.params.id]);if(!topic)fail(404,'Тема не найдена.');const offset=Math.max(0,Math.min(10000,Number(req.query.offset)||0)),replies=await db.all('SELECT r.*,u.display_name AS author FROM replies r JOIN users u ON u.id=r.author_id WHERE r.topic_id=? AND r.deleted=0 ORDER BY r.created_at,r.id LIMIT 51 OFFSET ?',[topic.id,offset]);res.json({topic,replies:replies.slice(0,50),hasMore:replies.length>50})})
 app.post('/api/forum/topics/:id/replies',auth.middleware,async(req,res)=>{const body=text(req.body.body),reply={id:id(),author_id:req.user.id,body,created_at:now()};await db.transaction(async tx=>{const topic=await tx.get('SELECT * FROM topics WHERE id=? AND deleted=0'+tx.lock,[req.params.id]);if(!topic)fail(404,'Тема не найдена.');if(topic.locked)fail(409,'Тема закрыта для ответов.');await tx.run('INSERT INTO replies(id,topic_id,author_id,body,created_at) VALUES(?,?,?,?,?)',[reply.id,topic.id,reply.author_id,body,reply.created_at]);await tx.run('UPDATE topics SET updated_at=? WHERE id=?',[reply.created_at,topic.id])});notify();res.status(201).json(reply)})
 app.patch('/api/forum/topics/:id',auth.middleware,async(req,res)=>{auth.moderator(req.user);const result=await db.run('UPDATE topics SET locked=?,pinned=?,updated_at=? WHERE id=? AND deleted=0',[req.body.locked===true?1:0,req.body.pinned===true?1:0,now(),req.params.id]);if(!Number(result.changes))fail(404,'Тема не найдена.');await db.run('INSERT INTO audit(id,actor_id,action,target_id,created_at) VALUES(?,?,?,?,?)',[id(),req.user.id,'moderate-topic',req.params.id,now()]);notify();res.json({ok:true})})
 app.delete('/api/forum/topics/:id',auth.middleware,async(req,res)=>{const topic=await db.get('SELECT * FROM topics WHERE id=? AND deleted=0',[req.params.id]);if(!topic)fail(404,'Тема не найдена.');if(topic.author_id!==req.user.id)auth.moderator(req.user);await db.run('UPDATE topics SET deleted=1 WHERE id=?',[topic.id]);notify();res.json({ok:true})})
 app.delete('/api/forum/replies/:id',auth.middleware,async(req,res)=>{const reply=await db.get('SELECT * FROM replies WHERE id=? AND deleted=0',[req.params.id]);if(!reply)fail(404,'Ответ не найден.');if(reply.author_id!==req.user.id)auth.moderator(req.user);await db.run('UPDATE replies SET deleted=1 WHERE id=?',[reply.id]);notify();res.json({ok:true})})
}
