import { mkdtemp, readdir, readFile, writeFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import assert from 'node:assert/strict'
import ts from 'typescript'
const directory=await mkdtemp(join(tmpdir(),'world6-rules-'))
try{
for(const file of await readdir(resolve('src'))){if(!file.endsWith('.ts'))continue;const source=await readFile(resolve('src',file),'utf8'),js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2023,module:ts.ModuleKind.ESNext}}).outputText.replace(/(from\s+['"]\.\/[^'"]+)(['"])/g,(_,a,b)=>a+'.mjs'+b);await writeFile(join(directory,file.replace(/\.ts$/,'.mjs')),js)}
const module=name=>import(pathToFileURL(join(directory,name+'.mjs')))
const model=await module('characterModel'),rules=await module('creationRules'),engine=await module('rpgEngine'),schema=await module('rpgSchema'),anatomy=await module('anatomyModel'),presets=await module('characterPresets'),transfer=await module('characterTransfer'),templates=await module('contentTemplates'),uploads=await module('uploadSafety'),races=await module('raceCatalog')
const body=await module('characterBody'),perception=await module('bodyPerception'),parameters=await module('rpgParameters')
let count=0
const test=(name,fn)=>{fn();count++;console.log('✓ '+name)}
const actor=(name='Тест')=>({...model.createDefaultCharacter(),name,id:'actor'})
test('Новый персонаж: 24 атрибута и валидная анатомия',()=>{const a=actor();assert.equal(model.attributeFields.length,24);assert(model.isCharacterDraft(a));assert(a.body.anatomy.structures.some(s=>s.kind==='skin'));assert(a.body.anatomy.structures.some(s=>s.kind==='muscle'))})
test('Миграция шести атрибутов и прежних рангов',()=>{const a=actor();a.profile.rank='magister';delete a.creation;delete a.profile.rankStep;delete a.profile.energy;a.attributes=Object.fromEntries(['strength','agility','constitution','intelligence','courage','charisma'].map(k=>[k,'10']));assert(model.isCharacterDraft(a));const n=model.normalizeCharacterDraft(a);assert.equal(n.profile.rank,'heavenlyLord');assert.equal(Object.keys(n.attributes).length,24);assert.equal(n.creation.skills.stealth,0);assert(model.isCharacterDraft(n))})
test('Только одна энергия; прежний теневой лист определяется по запасу',()=>{const a=actor();delete a.profile.energy;a.resources.mana={current:'0',maximum:'0'};a.resources.shadow={current:'20',maximum:'30'};const n=model.normalizeCharacterDraft(a);assert.equal(n.profile.energy,'shadow');const e=engine.effectiveActor({...n,id:'actor'},0);assert.equal(e.resources.mana.maximum,'0');assert.equal(e.resources.mana.current,'0')})
test('Последняя ступень ведёт к следующему рангу',()=>{const p=rules.nextProgression({...actor().profile,rank:'spellcaster',rankStep:3});assert.equal(p.rank,'elementalist');assert.equal(p.rankStep,1);assert.equal(rules.nextProgression({...p,rank:'heavenlyMonarch',rankStep:10}),null)})
test('Ранг, тренировка и обучение влияют на навык',()=>{const a=actor(),initial=rules.skillValue(a,'pickpocket');a.creation.skills.pickpocket=30;assert(rules.skillValue(a,'pickpocket')>initial);const v=rules.effectiveAttribute(a,'strength');a.profile.rank='heavenlyLord';assert(rules.effectiveAttribute(a,'strength')>v);a.creation.training.strength=5;assert(rules.effectiveAttribute(a,'strength')>v+5);assert.equal(rules.skillChance(10000,0),95);assert.equal(rules.skillChance(0,10000),5)})
test('Несколько освоенных школ снижают эффективность',()=>{const a=actor();a.profile.magic=[{schoolId:'fire',state:'mastered',notes:''}];const one=rules.magicEfficiency(a,'fire');a.profile.magic.push({schoolId:'water',state:'mastered',notes:''});assert(rules.magicEfficiency(a,'fire')<one)})
test('Все расы и формы валидны; общий HP не определяет смерть',()=>{for(const r of rules.raceTemplates)for(const form of r.transform?['base','partial','full']:['base']){const a=presets.applyRace(actor(),r.id,form,true);if(!model.isCharacterDraft(a))throw new Error(r.id+' '+form);assert.equal(a.resources.health.maximum,'0');if(a.rpg.physiology.mode!=='mana'&&a.rpg.physiology.mode!=='shadow')assert.equal(anatomy.automaticLife(a.body.anatomy,0,[],true).dead,false)}})
test('Смена формы сохраняет ранения и кровопотерю',()=>{let a=presets.applyRace(actor(),'demon');a.body.parts.torso.current=40;a.body.anatomy.structures.find(s=>s.id==='heart').current=55;a.rpg.physiology.currentMl=2800;const n=presets.applyRace(a,'demon','full');assert.equal(n.body.parts.torso.current,40);assert.equal(n.body.anatomy.structures.find(s=>s.id==='heart').current,55);assert.equal(n.rpg.physiology.currentMl,2800);assert(n.body.parts.leftWing)})
test('Драконид может быть магом воды и дышать огнём без маны',()=>{const a=presets.applyCharacterTemplate(actor(),'water-draconid'),innate=a.rpg.abilities.find(a=>a.innate);assert.equal(innate.cost.mana,0);assert.equal(rules.abilityLimit(a,innate),'');assert.equal(a.profile.magic[0].schoolId,'water')})
test('Сильный артефакт не экипируется и не даёт бонусов',()=>{const a=actor(),item={...templates.artifactTemplates[0].item,artifactLevel:12,minimumLevel:44,id:'artifact'};a.rpg.inventory=[engine.instantiateItem(item,'inventory')];assert.equal(rules.artifactCompatibility(a,item).ok,false);assert.throws(()=>engine.equipItem(a,'inventory',true),/аннигиляции/);assert.equal(a.rpg.inventory[0].equipped,false)})
test('Утрата жизненно важного органа приводит к смерти',()=>{const a=actor();a.body.anatomy.structures.find(s=>s.id==='brain').current=0;assert.equal(anatomy.automaticLife(a.body.anatomy,0).dead,true)})
test('Сохранение новых полей при JSON обмене',()=>{const a=presets.applyCharacterTemplate(actor(),'water-draconid');a.creation.appearance.height=2;a.rpg.inventory=[engine.instantiateItem({...templates.artifactTemplates[1].item,id:'staff'},'staff-instance')];const json=transfer.createCharacterArchive([a],new Date().toISOString()),result=transfer.parseCharacterArchive(json);assert(result.ok);const n=result.preview.characters[0];assert.equal(n.creation.appearance.height,2);assert.equal(n.rpg.inventory[0].artifactLevel,3);assert.equal(n.rpg.abilities[0].raceId,'draconid');assert(model.isCharacterDraft(n))})
test('Некорректные и слишком большие загрузки отвергаются',()=>{assert.equal(transfer.parseCharacterArchive('x'.repeat(transfer.MAX_IMPORT_BYTES+1)).ok,false);const a=actor();a.creation.skills.pickpocket=101;assert.equal(model.isCharacterDraft(a),false);assert.equal(schema.isItem({...templates.artifactTemplates[0].item,artifactLevel:13}),false);assert.equal(schema.isAbility({...schema.emptyAbility(),name:'Ошибка',attributeRequirements:{unknown:1}}),false)})
test('Все шаблоны магии и артефактов проходят схему',()=>{assert(templates.spellTemplates.every(schema.isAbilityTemplate));assert(templates.artifactTemplates.every(t=>schema.isItem(t.item)))})
test('Рост монотонен на всех границах рангов',()=>{let a=actor();a.profile.rank='mortal';a.profile.rankStep=1;let value=rules.effectiveAttribute(a,'strength');for(let i=0;i<40;i++){const next=rules.nextProgression(a.profile);if(!next)break;a.profile=next;const current=rules.effectiveAttribute(a,'strength');assert(current>value);value=current}})
test('Ранение скрытого крыла возвращается после повторной трансформации',()=>{let a=presets.applyRace(actor(),'demon','full');a.body.parts.leftWing.current=30;a.body.anatomy.structures.find(s=>s.id==='leftWing-skin').current=20;a=presets.applyRace(a,'demon','base');a=presets.applyRace(a,'demon','full');assert.equal(a.body.parts.leftWing.current,30);assert.equal(a.body.anatomy.structures.find(s=>s.id==='leftWing-skin').current,20);assert(model.isCharacterDraft(a))})
test('Артефакт расходует свой запас и принимает заряд персонажа',()=>{let a=actor();a.rpg.inventory=[engine.instantiateItem({...templates.artifactTemplates[0].item,id:'blade'},'blade-instance')];a=engine.equipItem(a,'blade-instance',true);const mana=a.resources.mana.current;a=engine.activateArtifact(a,'blade-instance',0);assert.equal(a.rpg.inventory[0].artifactCharge,18);assert.equal(a.resources.mana.current,mana);a=engine.rechargeArtifact(a,'blade-instance',2,0);assert.equal(a.rpg.inventory[0].artifactCharge,20);assert.equal(Number(a.resources.mana.current),Number(mana)-2);assert(model.isCharacterDraft(a))})
test('Артефакт нельзя сделать безопасным снижением ручного требования',()=>{const a=actor(),i={...templates.artifactTemplates[0].item,artifactLevel:12,minimumLevel:0};assert.equal(rules.artifactCompatibility(a,i).ok,false)})
test('Восстановление энергии учитывает время и не наполняет вторую энергию',()=>{const a=actor();a.resources.mana.current='20';const world=engine.advanceWorld({characters:[a],campaign:schema.emptyCampaign()},10,'regen');assert(Number(world.characters[0].resources.mana.current)>20);assert.equal(world.characters[0].resources.shadow.current,'0');assert(model.isCharacterDraft(world.characters[0]))})
test('Блокировка каналов запрещает магическое действие',()=>{const a=actor();a.profile.magic=[{schoolId:'fire',state:'mastered',notes:''}];a.rpg.abilities=[{...templates.spellTemplates.find(s=>s.id==='spell-fire-basic'),id:'fire',templateId:'fire',approved:true}];a.rpg.effects=[{id:'blocked',name:'Блок',strength:1,stackKey:'block',stacking:'refresh',modifiers:[],statusEffects:['channel-block'],expiresAt:null,bloodMlPerSecond:0,substituteMl:0,ownerId:'',castId:''}];const input={region:'torso',distanceM:0,accessible:true,conditionsConfirmed:true,canSpeak:true,armorPath:'covered',gapConfirmed:false,criticalChance:0,dodgeChance:0,criticalContactFactor:1,manualLocal:10,manualSystemic:100,bleedingMlPerSecond:0,injury:'',note:''};const plan=engine.makeActionPlan({characters:[a],campaign:schema.emptyCampaign()},a.id,'fire',a.id,input,'blocked-event');assert.equal(plan.ok,false);assert.match(plan.message,/заблокированы/);assert.equal(engine.evaluatedParameters(a,0).controlPower,'0')})
test('Размер изображения проверяется по заголовку до декодирования',()=>{const b=new Uint8Array(24),v=new DataView(b.buffer);b.set([137,80,78,71],0);b.set([73,72,68,82],12);v.setUint32(16,4000);v.setUint32(20,3000);assert.equal(uploads.imageDimensions(b,'image/png').width,4000);v.setUint32(16,100000);assert.throws(()=>uploads.imageDimensions(b,'image/png'),/превышает/);assert.throws(()=>uploads.imageDimensions(b,'image/jpeg'),/Заголовок/)})
test('Порядок рангов: Заклинатель до Элементалиста',()=>{const a=rules.nextProgression({...actor().profile,rank:'mortal',rankStep:3});assert.equal(a.rank,'spellcaster');const b=rules.nextProgression({...a,rankStep:3});assert.equal(b.rank,'elementalist')})
test('Суставы соединяют существующие кости и сохраняют повреждения',()=>{const a=actor(),joint=a.body.anatomy.structures.find(s=>s.id==='left-elbow');assert.equal(joint.kind,'joint');assert(joint.connections.length>=2);assert(joint.connections.every(id=>a.body.anatomy.structures.some(s=>s.id===id)));joint.current=30;const copied=anatomy.copyDetailedAnatomy(a.body.anatomy);assert.equal(copied.structures.find(s=>s.id===joint.id).current,30);assert(anatomy.isDetailedAnatomy(copied));joint.connections.push('invalid reference');assert.equal(copied.structures.find(s=>s.id==='left-elbow').connections.length,3)})
test('Старый лист получает суставы без исцеления органов',()=>{const a=actor();a.body.anatomy.structures=a.body.anatomy.structures.filter(s=>s.kind!=='joint');a.body.anatomy.structures.find(s=>s.id==='heart').current=40;const n=model.normalizeCharacterDraft(a);assert.equal(n.body.anatomy.structures.find(s=>s.id==='heart').current,40);assert(n.body.anatomy.structures.some(s=>s.kind==='joint'));assert(model.isCharacterDraft(n))})
test('Подтипы зверолюдей и объединение ноктари',()=>{assert.equal(races.raceById('draconid').parentId,'beastfolk');assert.equal(races.raceById('marine').parentId,'beastfolk');assert.equal(races.raceById('shadowborn').id,'noctari');assert(!races.raceTemplates.some(r=>r.id==='shadowborn'));const a=actor();a.creation.raceId='shadowborn';const n=model.normalizeCharacterDraft(a);assert.equal(n.creation.raceId,'noctari');assert(model.isCharacterDraft(n))})
test('Собственная раса, жабры и бонусы переживают JSON обмен',()=>{let a=actor();const r={...structuredClone(races.raceById('human')),id:'custom-race',name:'Своя раса',gills:true,bonuses:{strength:12},learning:1.5};a.creation.customRaces=[r];a=presets.applyRace(a,r.id);assert.equal(rules.effectiveAttribute(a,'strength'),rules.effectiveAttribute({...a,creation:{...a.creation,raceId:'human'}},'strength')+12);assert(a.body.anatomy.structures.some(s=>s.id==='left-gill'));assert(model.isCharacterDraft(a));const result=transfer.parseCharacterArchive(transfer.createCharacterArchive([a],new Date().toISOString()));assert(result.ok);assert.equal(result.preview.characters[0].creation.customRaces[0].name,'Своя раса');assert.equal(result.preview.characters[0].creation.raceId,'custom-race')})
test('Человеческое обучение реально повышает обученный навык',()=>{const a=actor();a.creation.raceId='human';a.creation.skills.forging=30;const human=rules.skillValue(a,'forging');const copy=structuredClone(a);copy.creation.customRaces=[{...structuredClone(races.raceById('human')),learning:1}];assert(human>rules.skillValue(copy,'forging'));assert(rules.effectiveAttribute(a,'coordination')>Number(a.attributes.coordination))})
test('Расширенные формы артефактов и размеры сохраняются',()=>{for(const shape of ['dagger','axe','bow','amulet','helmet','armor','potion']){const item={...templates.artifactTemplates[0].item,shape,modelLength:1.4,modelWidth:.8,modelDepth:.4};assert(schema.isItem(item));assert.equal(schema.copyItem(item).modelLength,1.4)}assert.equal(schema.isItem({...templates.artifactTemplates[0].item,modelLength:100}),false);assert.equal(races.isRaceTemplate({...races.raceById('human'),learning:100}),false)})
test('Птичья физиология и тип крыльев сохраняются',()=>{let a=presets.applyRace(actor(),'birdkin','full');assert.equal(a.body.anatomy.form,'bird');assert.equal(a.body.anatomy.wingStyle,'feathers');for(const id of ['air-sacs','crop','gizzard','syrinx'])assert(a.body.anatomy.structures.some(s=>s.id===id));assert(model.isCharacterDraft(a));const copy=anatomy.copyDetailedAnatomy(a.body.anatomy);assert.equal(copy.wingStyle,'feathers');assert.equal(copy.structures.find(s=>s.id==='sternum').name,'Грудина и киль')})

const input={region:'torso',distanceM:0,accessible:true,conditionsConfirmed:true,canSpeak:true,armorPath:'covered',gapConfirmed:false,criticalChance:0,dodgeChance:0,criticalContactFactor:1,manualLocal:0,manualSystemic:0,bleedingMlPerSecond:0,injury:'',note:''}
const effect=(id,percent,strength=1)=>({id,name:id,strength,stackKey:'same',stacking:'strongest',modifiers:[{parameter:'controlPower',flat:0,percent}],statusEffects:[],expiresAt:null,bloodMlPerSecond:0,substituteMl:0,ownerId:'',castId:''})
test('У каждого крыла есть связанный скелет, мышцы, сосуды и нервы',()=>{const a=presets.applyRace(actor(),'demon','full');for(const side of ['left','right']){const ss=a.body.anatomy.structures.filter(s=>s.region===side+'Wing');for(const kind of ['skin','bone','joint','muscle','vessel','organ'])assert(ss.some(s=>s.kind===kind));const joints=ss.filter(s=>s.kind==='joint');assert.equal(joints.length,3);for(const j of joints)assert(j.connections.every(id=>ss.some(s=>s.id===id&&s.kind==='bone')))}assert(body.bodyConsequences(a.body).canFly);assert(model.isCharacterDraft(a))})
test('Старые крылья дополняются без исцеления и изменения исходного листа',()=>{const a=presets.applyRace(actor(),'demon','full');a.body.anatomy.structures=a.body.anatomy.structures.filter(s=>!s.region.endsWith('Wing')||['left-wing-bone','right-wing-bone','leftWing-skin','rightWing-skin'].includes(s.id));a.body.anatomy.structures.find(s=>s.id==='left-wing-bone').current=0;const original=JSON.stringify(a),n=model.normalizeCharacterDraft(a);assert.equal(JSON.stringify(a),original);assert(n.body.anatomy.structures.some(s=>s.id==='left-wing-nerve'));assert.equal(n.body.anatomy.structures.find(s=>s.id==='left-wing-bone').current,0);assert.equal(body.bodyConsequences(n.body).canFly,false)})
test('Повреждение крыла уменьшает мощность; блокировка нерва и утрата опоры запрещают полёт',()=>{const a=presets.applyRace(actor(),'demon','full'),muscle=a.body.anatomy.structures.find(s=>s.id==='left-wing-elevator');muscle.current=50;assert.equal(body.bodyConsequences(a.body).flightFactor,.5);muscle.current=25;assert.equal(body.bodyConsequences(a.body).canFly,false);muscle.current=100;const nerve=a.body.anatomy.structures.find(s=>s.id==='right-wing-nerve');nerve.injuries=[{id:'nerve-harm',label:'Нарушение нерва',blocksUse:true,diagnosed:false}];assert.equal(body.bodyConsequences(a.body).canFly,false);assert.match(body.bodyConsequences(a.body).flightReasons.join(' '),/Правое крыло/)})
test('Перистые крылья имеют покров, а птице нужны обе рабочие передние конечности',()=>{const a=presets.applyRace(actor(),'angel','base');assert(a.body.anatomy.structures.some(s=>s.id==='left-wing-feathers'));assert(!a.body.anatomy.structures.some(s=>s.id==='left-wing-membrane'));const b=presets.applyRace(actor(),'birdkin','full');assert(body.bodyConsequences(b.body).canFly);assert.equal(body.bodyConsequences(b.body).twoHands,false);b.body.parts.rightHand.current=0;assert.equal(body.bodyConsequences(b.body).canFly,false);assert.equal(body.bodyConsequences(b.body).rightHand,false)})
test('Внутреннее ранение даёт ощущения без скрытого диагноза и численного HP',()=>{const a=presets.applyRace(actor(),'demon','full'),nerve=a.body.anatomy.structures.find(s=>s.id==='left-wing-nerve');nerve.current=20;nerve.injuries=[{id:'hidden',label:'Разрыв нерва',blocksUse:true,diagnosed:false}];assert.equal(a.body.parts.leftWing.current,100);let p=perception.perceivedBody(a.body).find(p=>p.region==='leftWing');assert(p.symptoms.length);assert.equal(p.diagnoses.length,0);assert(!JSON.stringify(p).includes('Разрыв нерва'));nerve.injuries[0].diagnosed=true;p=perception.perceivedBody(a.body).find(p=>p.region==='leftWing');assert.match(p.diagnoses[0],/Разрыв нерва/)})
test('Полёт не требует работающих ног; действие блокируется повреждением крыла',()=>{const a=presets.applyRace(actor(),'demon','full');a.body.parts.leftLeg.current=0;a.body.parts.rightLeg.current=0;const flight={...schema.emptyAbility(),id:'fly',templateId:'fly',name:'Взмах',approved:true,flight:true,movement:true,hands:'none',mechanism:'effect'};a.rpg.abilities=[flight];assert.equal(body.bodyConsequences(a.body).movementFactor,0);let p=engine.makeActionPlan({characters:[a],campaign:schema.emptyCampaign()},a.id,'fly',a.id,input,'flight-ok',()=>.9);assert(p.ok,p.message);a.body.anatomy.structures.find(s=>s.id==='left-wing-bone').current=0;p=engine.makeActionPlan({characters:[a],campaign:schema.emptyCampaign()},a.id,'fly',a.id,input,'flight-fail');assert.equal(p.ok,false);assert.match(p.message,/крыл/);assert.equal(a.rpg.casts.length,0)})
test('Все реальные ступени имеют монотонные ограничения магии',()=>{assert.equal(rules.developmentStages.length,29);let previous=0;for(const stage of rules.developmentStages){const a=actor();const index=Math.floor(stage.value/10);a.profile.rank=['mortal','spellcaster','elementalist','heavenlyLord','heavenlyMonarch'][index];a.profile.rankStep=stage.value%10+1;const cap=rules.abilityLimits(a.profile);assert(cap.power>previous);previous=cap.power;const spell={...schema.emptyAbility(),schoolId:'fire',strength:cap.power+1,rangeM:cap.range+1,duration:cap.duration+1,attributeRequirements:{magicControl:10000}};const issues=rules.abilityDiagnostics(a,spell);assert(issues.some(s=>s.includes('Сила')));assert(issues.some(s=>s.includes('Дальность')));assert(issues.some(s=>s.includes('Длительность')));assert(issues.some(s=>s.includes('Магический контроль')))}})
test('Известная и изучаемая школа не разрешают заклинание; ветвь использует основу',()=>{const a=actor(),spell={...schema.emptyAbility(),schoolId:'sand'};for(const state of ['known','studying']){a.profile.magic=[{schoolId:'earth',state,notes:''}];assert.match(rules.abilityLimit(a,spell),/не освоена/)}a.profile.magic[0].state='mastered';assert.equal(rules.abilityLimit(a,spell),'');assert.equal(rules.castingSchool('sand'),'earth')})
test('Техника Тени сохраняет основу в JSON и соблюдает строгий выбор энергии',()=>{const a=actor(),spell={...schema.emptyAbility(),id:'tech',templateId:'tech',approved:true,schoolId:'healing',basisSchoolId:'shadows',name:'Теневая техника'};assert(schema.isAbility(spell));a.profile.magic=[{schoolId:'shadows',state:'mastered',notes:''}];assert.match(rules.abilityDiagnostics(a,spell).join(' '),/Тень/);a.profile.energy='shadow';assert.equal(rules.abilityLimit(a,spell),'');a.rpg.abilities=[spell];const result=transfer.parseCharacterArchive(transfer.createCharacterArchive([a],new Date().toISOString()));assert(result.ok);assert.equal(result.preview.characters[0].rpg.abilities[0].basisSchoolId,'shadows');spell.cost.mana=1;assert.match(rules.abilityLimit(a,spell),/другой тип энергии/);assert.equal(schema.isAbility({...spell,basisSchoolId:'healing'}),false)})
test('Усиленная магия не обходит потолок силы ранга',()=>{const a=actor();a.profile.rank='mortal';a.profile.rankStep=1;a.profile.magic=[{schoolId:'fire',state:'mastered',notes:''}];a.creation.skills.spellcraft=100;const spell={...schema.emptyAbility(),id:'cap',templateId:'cap',approved:true,schoolId:'fire',strength:20,mastery:100,name:'Проверка потолка',mechanism:'effect'};a.rpg.abilities=[spell];const p=engine.makeActionPlan({characters:[a],campaign:schema.emptyCampaign()},a.id,'cap',a.id,input,'magic-cap');assert(p.ok,p.message);assert.equal(p.plan.world.characters[0].rpg.effects[0].strength,20);assert.match(p.plan.details,/применена сила: 20/)})
test('Объяснение формулы совпадает с итогом и включает источники изменений',()=>{const a=actor();a.rpg.effects=[effect('focus',20)];const result=parameters.parameterCalculation(a,0),trace=result.traces.controlPower;assert.equal(result.values.controlPower,engine.evaluatedParameters(a,0).controlPower);assert.equal(trace.basis,trace.base+trace.terms.reduce((sum,t)=>sum+t.contribution,0)+trace.adjustment);assert.equal(trace.beforeLimit,(trace.basis+trace.flat)*(1+trace.percent/100));assert.equal(trace.result,result.values.controlPower);assert.equal(trace.modifiers[0].source,'Эффект: focus');assert.equal(result.values.maximumHealth,'0');assert.equal(result.values.maximumShadow,'0')})
test('Формулы: ручной режим, поправка, предел шанса и переполнение',()=>{const a=actor(),f=a.rpg.formulas.find(f=>f.parameter==='spellAccuracy');f.mode='manual';a.statistics.spellAccuracy='80';assert.equal(parameters.parameterCalculation(a,0).values.spellAccuracy,'80');f.mode='adjusted';f.base=99;f.adjustment=4;f.weights=Object.fromEntries(Object.keys(f.weights).map(k=>[k,0]));const trace=parameters.parameterCalculation(a,0).traces.spellAccuracy;assert.equal(trace.basis,103);assert.equal(trace.result,'100');assert(trace.limits.length);f.base=1e12;f.weights.strength=1e12;assert.throws(()=>parameters.parameterCalculation(a,0),/допустимый диапазон/)})
test('Боль и кровопотеря отражаются в расчёте; здоровый лист не меняется',()=>{const a=actor(),initial=JSON.stringify(a),healthy=parameters.parameterCalculation(a,0);assert.equal(JSON.stringify(a),initial);a.body.anatomy.structures.find(s=>s.id==='left-biceps').current=0;a.rpg.physiology.currentMl=2600;const result=parameters.parameterCalculation(a,0);assert(Number(result.values.concentrationPower)<Number(healthy.values.concentrationPower));assert(result.traces.concentrationPower.modifiers.some(m=>m.source==='Боль от ранений'));assert(Object.values(result.traces).some(t=>t.modifiers.some(m=>m.source==='Дефицит жизненного носителя')));assert(rules.skillValue(a,'ranged')<rules.skillValue(actor(),'ranged'))})
test('Навыки и параметры одинаково исключают слабые и истёкшие эффекты',()=>{const a=actor();a.rpg.effects=[effect('weak',10,1),effect('strong',30,2),{...effect('expired',90,3),expiresAt:1}];const b=structuredClone(a);b.rpg.effects=[effect('strong',30,2)];assert.equal(rules.skillValue(a,'spellcraft',2),rules.skillValue(b,'spellcraft',2));assert.equal(engine.evaluatedParameters(a,2).controlPower,engine.evaluatedParameters(b,2).controlPower);const c=rules.skillBreakdown(a,'spellcraft',2);assert.equal(c.value,rules.skillValue(a,'spellcraft',2));assert.equal(c.aptitude,c.terms.reduce((s,t)=>s+t.value*t.weight,0))})
test('Старая птица и смена формы сохраняют ранения, но не получают человеческие руки',()=>{let a=presets.applyRace(actor(),'birdkin','full');delete a.body.parts.leftArm.group;delete a.body.parts.leftHand.group;delete a.body.parts.rightArm.group;delete a.body.parts.rightHand.group;a.body.anatomy.structures.find(s=>s.id==='left-biceps').current=45;const n=model.normalizeCharacterDraft(a);assert.equal(body.bodyConsequences(n.body).twoHands,false);assert.equal(n.body.anatomy.structures.find(s=>s.id==='left-biceps').current,45);assert(body.bodyConsequences(n.body).canFly);a=presets.applyRace(n,'birdkin','base');assert.equal(body.bodyConsequences(a.body).twoHands,true);assert.equal(a.body.anatomy.structures.find(s=>s.id==='left-biceps').current,45);a=presets.applyRace(a,'birdkin','full');assert.equal(body.bodyConsequences(a.body).twoHands,false);assert.equal(a.body.anatomy.structures.find(s=>s.id==='left-biceps').current,45)})
console.log(`Проверено: ${count} сценариев.`)
}finally{await rm(directory,{recursive:true,force:true})}
