import { useEffect,useState } from 'react'
import { useOnline } from './onlineContext'
import { CommunityShell } from './NetworkCommon'
import { roleLabels } from './onlineTypes'
import { Check,TextField } from './RpgControls'
export default function AccountPanel(){
 const online=useOnline(),[mode,setMode]=useState<'login'|'register'|'recover'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[agree,setAgree]=useState(false),[factor,setFactor]=useState(''),[qr,setQr]=useState(''),[code,setCode]=useState(''),[secret,setSecret]=useState(''),[newPassword,setNewPassword]=useState('')
 useEffect(()=>{if(!online.user?.mfaRequired||!online.supabase)return;let stopped=false;void online.supabase.auth.mfa.listFactors().then(({data,error})=>{if(stopped)return;if(error){setMessage(error.message);return}const verified=data.totp.find(f=>f.status==='verified');if(verified)setFactor(verified.id)});return()=>{stopped=true}},[online.user?.mfaRequired,online.supabase])
 async function run(fn:()=>Promise<string|void>){setBusy(true);try{setMessage(await fn()||'Готово.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 async function enroll(){if(!online.supabase)return;const {data,error}=await online.supabase.auth.mfa.listFactors();if(error)throw error;const existing=data.totp.find(f=>f.status==='verified');if(existing){setFactor(existing.id);return 'Введи код из приложения аутентификации.'}for(const f of data.totp.filter(f=>f.status!=='verified'))await online.supabase.auth.mfa.unenroll({factorId:f.id});const result=await online.supabase.auth.mfa.enroll({factorType:'totp',friendlyName:'Мир 6'});if(result.error)throw result.error;setFactor(result.data.id);setQr(result.data.totp.qr_code);setSecret(result.data.totp.secret);return 'Добавь QR-код в приложение аутентификации и введи одноразовый код.'}
 return <CommunityShell title={online.user?'Твой аккаунт':'Вход в Мир 6'}>
 {online.error&&<p className="w6-error">{online.error}</p>}{online.loading&&<p>Подключаемся к серверу…</p>}{!online.user&&online.error&&online.supabase&&<button className="w6-button" disabled={busy} onClick={()=>void run(()=>online.logout())}>Сбросить текущую сессию</button>}
 {online.config?.authMode==='local'&&<p className="w6-notice">Локальная проверка аккаунтов. Для публичного сайта подключается регистрация с подтверждением email через Supabase.</p>}
 {online.user?<><div className="w6-account-card"><span className="w6-account-monogram">{online.user.displayName.slice(0,1).toUpperCase()}</span><div><h2>{online.user.displayName}</h2><p>{roleLabels[online.user.role]} · {online.connected?'Связь с сервером установлена':'Переподключаемся к серверу'}</p></div></div>
 <form className="w6-form w6-fieldset" onSubmit={e=>{e.preventDefault();void run(async()=>{await online.request('/me',{method:'PATCH',body:JSON.stringify({displayName:name})});await online.reloadUser();return 'Имя обновлено.'})}}><TextField label="Новое имя в сообществе" value={name} onChange={setName} max={40}/><button className="w6-button" disabled={busy||!name.trim()}>Изменить имя</button></form>
 {online.supabase&&<div className="w6-fieldset"><h3>Второй фактор</h3><p>{online.user.mfaRequired?'Подтверди код, чтобы завершить вход или получить доступ к привилегированным действиям.':'Второй фактор защищает аккаунт дополнительным кодом. Для администрации и редакторов мира он обязателен.'}</p><button className="w6-button" disabled={busy} onClick={()=>void run(enroll)}>Настроить или подтвердить второй фактор</button>{qr&&<img className="w6-mfa-qr" src={qr.startsWith('data:')?qr:'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(qr)} alt="QR-код настройки второго фактора"/>}{secret&&<p className="w6-break">Если QR-код не читается, добавь этот ключ в аутентификатор вручную: <code>{secret}</code></p>}{factor&&<form className="w6-form" onSubmit={e=>{e.preventDefault();void run(async()=>{const {error}=await online.supabase!.auth.mfa.challengeAndVerify({factorId:factor,code});if(error)throw error;setCode('');setQr('');setSecret('');setFactor('');await online.reloadUser();return 'Второй фактор подтверждён.'})}}><label className="w6-field"><span>Код аутентификатора</span><input required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.currentTarget.value)}/></label><button className="w6-button" disabled={busy}>Подтвердить код</button></form>}</div>}
 {online.supabase&&<form className="w6-fieldset w6-form" onSubmit={e=>{e.preventDefault();void run(async()=>{const {error}=await online.supabase!.auth.updateUser({password:newPassword});if(error)throw error;setNewPassword('');return 'Пароль обновлён.'})}}><h3>Изменить пароль</h3><label className="w6-field"><span>Новый пароль</span><input required type="password" autoComplete="new-password" minLength={12} maxLength={128} value={newPassword} onChange={e=>setNewPassword(e.currentTarget.value)}/></label><button className="w6-button" disabled={busy||online.user.mfaRequired}>Сохранить пароль</button></form>}
 <button className="w6-button" disabled={busy} onClick={()=>void run(()=>online.logout())}>Выйти из аккаунта</button></>:<><div className="w6-modes">{([['login','Вход'],['register','Регистрация'],['recover','Забыли пароль?']] as const).map(([id,label])=><button type="button" key={id} className={'w6-button'+(mode===id?' w6-active':'')} onClick={()=>setMode(id)}>{label}</button>)}</div>
 <form className="w6-form w6-auth-form" onSubmit={e=>{e.preventDefault();void run(async()=>{if(mode==='recover'){if(!online.supabase)throw new Error('Для локальной проверки восстановление через email не подключено.');const {error}=await online.supabase.auth.resetPasswordForEmail(email,{redirectTo:new URL(import.meta.env.BASE_URL,window.location.href).href});if(error)throw error;return 'Если аккаунт существует, письмо для восстановления отправлено.'}return mode==='login'?online.login(email,password):online.register(email,password,name)})}}>
 {mode==='register'&&<TextField label="Имя в сообществе" value={name} onChange={setName} max={40}/>}<label className="w6-field"><span>Email</span><input required type="email" autoComplete="email" maxLength={254} value={email} onChange={e=>setEmail(e.currentTarget.value)}/></label>{mode!=='recover'&&<label className="w6-field"><span>Пароль</span><input aria-label="Пароль" required type="password" minLength={mode==='register'?12:1} maxLength={128} autoComplete={mode==='register'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.currentTarget.value)}/><small>{mode==='register'?'Минимум 12 символов.':''}</small></label>}{mode==='register'&&<Check label="Принимаю правила сообщества: уважение к участникам и отсутствие спама" value={agree} onChange={setAgree}/>}
 <button className="w6-button w6-primary" disabled={busy||!online.config||mode==='register'&&(!agree||!name.trim())}>{busy?'Подождите…':mode==='register'?'Зарегистрироваться':mode==='recover'?'Отправить письмо':'Войти'}</button></form></>}
 {online.recovering&&<form className="w6-fieldset w6-form" onSubmit={e=>{e.preventDefault();void run(async()=>{const {error}=await online.supabase!.auth.updateUser({password});if(error)throw error;online.clearRecovery();return 'Новый пароль сохранён.'})}}><h3>Новый пароль</h3><label className="w6-field"><span>Новый пароль аккаунта</span><input type="password" required minLength={12} maxLength={128} value={password} onChange={e=>setPassword(e.currentTarget.value)}/></label><button className="w6-button" disabled={busy}>Сохранить новый пароль</button></form>}
 <p className="w6-notice" role="status">{message}</p></CommunityShell>
}
