import { useState } from 'react'
import { useOnline } from './onlineContext'
import { useRemote } from './onlineHooks'
import { CommunityShell,RemoteStatus,formatDate } from './NetworkCommon'
import type { OnlineUser } from './onlineTypes'
export default function AdminPanel(){
 const {user,request,refresh}=useOnline(),users=useRemote<(OnlineUser&{createdAt:string})[]>(user?'/admin/users':null),audit=useRemote<{id:string;actor:string;action:string;target_id:string;created_at:string}[]>(user?'/admin/audit':null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 async function update(id:string,patch:object){setBusy(true);try{await request('/admin/users/'+id,{method:'PATCH',body:JSON.stringify(patch)});refresh();setMessage('Доступ обновлён и записан в журнал.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <CommunityShell title="Управление сайтом"><p className="w6-copy">Глобальные роли управляют сайтом. Мастером отдельного лобби становится его создатель; это не даёт административного доступа.</p>{user?.mfaRequired&&<p className="w6-notice">Подтверди второй фактор в разделе «Аккаунт».</p>}<RemoteStatus error={users.error} loading={users.loading}/><div className="w6-table-scroll"><table className="w6-table"><thead><tr><th>Участник</th><th>Роль</th><th>Доступ</th></tr></thead><tbody>{users.value?.map(u=><tr key={u.id}><td>{u.displayName}<small className="w6-block">{u.email}</small></td><td>{user?.role==='OWNER'&&u.role!=='OWNER'?<select aria-label={'Роль: '+u.displayName} value={u.role} disabled={busy||u.id===user.id} onChange={e=>void update(u.id,{role:e.currentTarget.value})}>{['PLAYER','GM','WORLD_EDITOR','ADMIN'].map(r=><option key={r}>{r}</option>)}</select>:u.role}</td><td><button className="w6-button" disabled={busy||u.role==='OWNER'||u.id===user?.id} onClick={()=>{if(window.confirm((u.disabled?'Разблокировать ':'Заблокировать ')+u.displayName+'?'))void update(u.id,{disabled:!u.disabled})}}>{u.disabled?'Разблокировать':'Заблокировать'}</button></td></tr>)}</tbody></table></div><details className="w6-fieldset"><summary>Журнал административных действий</summary><RemoteStatus error={audit.error} loading={audit.loading}/>{audit.value?.map(a=><article key={a.id} className="w6-entry"><strong>{a.actor} · {a.action}</strong><p className="w6-break">{formatDate(a.created_at)} · {a.target_id}</p></article>)}</details><p role="status" className="w6-notice">{message}</p></CommunityShell>
}
