import HitPath from './HitPath'
import { useState } from 'react'
import AnatomyAtlas from './AnatomyAtlas'
import StructureIllustration from './StructureIllustration'
import { anatomyForms, inferAnatomyForm, createDetailedAnatomy, copyDetailedAnatomy, isStructure, isDetailedAnatomy, kindLabels, structureBlocked, automaticLife } from './anatomyModel'
import { bodyConsequences } from './characterBody'
import type { AnatomyForm, AnatomyStructure } from './anatomyModel'
import { bodyRegionDefs, cloneBody, emptyBody } from './characterBody'
import type { Actor } from './rpgEngine'
import { masterLifeOverride, physiologyStatus, recalculateLife } from './rpgEngine'
import { Field, NumberField, TextField, Check } from './RpgControls'
import { StateIcon } from './VisualElements'
type Props={actor:Actor;seconds:number;onChange:(a:Actor)=>void}
export default function AnatomyPanel({actor,seconds,onChange}:Props){
 const [region,setRegion]=useState('torso'),[structureId,setStructure]=useState('heart'),[form,setForm]=useState<AnatomyForm>(()=>actor.body.anatomy?.form??inferAnatomyForm(actor.rpg.physiology.race+' '+actor.profile.origin,Object.keys(actor.body.parts))),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[damagedOnly,setDamagedOnly]=useState(false),[playerView,setPlayerView]=useState(false)
 const [lifeSettings,setLifeSettings]=useState<{unconsciousDeficit:number;lethalDeficit:number}|null>(null)
 const [editing,setEditing]=useState<AnatomyStructure|null>(null),[reason,setReason]=useState(''),[injury,setInjury]=useState(''),[state,setState]=useState<'awake'|'unconscious'|'dead'>('unconscious'),[message,setMessage]=useState('')
 const [wingStyle,setWingStyle]=useState<'membrane'|'feathers'>(actor.body.anatomy?.wingStyle??'membrane')
 const anatomy=actor.body.anatomy,regions=bodyRegionDefs(actor.body),selectedRegion=actor.body.parts[region]?region:regions[0].key
 const selected=anatomy?.structures.find(s=>s.id===structureId),status=physiologyStatus(actor,seconds),life=anatomy?automaticLife(anatomy,status.deficit,Object.entries(actor.body.parts).filter(([,p])=>!p.present).map(([key])=>key),false):null
 const visible=(anatomy?.structures??[]).filter(s=>(!filter||s.kind===filter)&&s.region===selectedRegion&&(!damagedOnly||s.current<s.maximum||s.injuries.length)&&(!query||s.name.toLocaleLowerCase().includes(query.toLocaleLowerCase()))&&(!playerView||s.kind==='skin'||s.injuries.some(i=>i.diagnosed)))
 function commit(next:Actor,text:string,record=true){try{const logged=record?{...next,rpg:{...next.rpg,logs:[...next.rpg.logs,{id:crypto.randomUUID(),seconds,text,details:reason.trim()||'Настройка локального листа.'}].slice(-200)}}:next;onChange(recalculateLife(logged,seconds,crypto.randomUUID()));setMessage(text+' Сохрани изменения.')}catch(e){setMessage((e as Error).message)}}
 function addFeature(feature:'horns'|'tail'|'arms'){
  if(!anatomy)return
  const body=cloneBody(actor.body),keys=feature==='horns'?['leftHorn','rightHorn']:feature==='tail'?['tail']:['extraLeftArm','extraRightArm']
  const newKeys=keys.filter(k=>!body.parts[k]);if(!newKeys.length){setMessage('Эта особенность уже добавлена.');return}
  if(Object.keys(body.parts).length+newKeys.length>64||anatomy.structures.length+newKeys.length*3>512){setMessage('Достигнут предел частей или структур.');return}
  for(const k of newKeys)body.parts[k]={...emptyBody().parts.torso,label:({leftHorn:'Левый рог',rightHorn:'Правый рог',tail:'Хвост',extraLeftArm:'Дополнительная левая рука',extraRightArm:'Дополнительная правая рука'} as Record<string,string>)[k],group:'other'}
  const a=copyDetailedAnatomy(anatomy),extra=createDetailedAnatomy(anatomy.form,newKeys).structures
  for(const k of newKeys){const skin=extra.find(s=>s.region===k)!;extra.push({...skin,id:k+'-support',name:feature==='horns'?'Основа рога':feature==='tail'?'Опора хвоста':'Кости дополнительной руки',kind:'bone',depth:.5,rx:.12,ry:.4,thresholdJ:12,joulesPerHp:4})}
  a.structures.push(...extra);body.anatomy=a;commit({...actor,body},'Особенность тела добавлена. Задай HP новой области и её требования.')
 }
 function connect(){
  setLifeSettings(null)
  if(anatomy&&!window.confirm('Заменить подробную анатомию? Состояние внутренних структур будет сброшено. Локальные HP, кровь и отметка смерти сохранятся.'))return
  const body=cloneBody(actor.body)
  if(form==='winged')for(const side of ['left','right'])if(!body.parts[side+'Wing'])body.parts[side+'Wing']={...emptyBody().parts.torso,current:100,maximum:100,label:(side==='left'?'Левое':'Правое')+' крыло',group:'other'}
  if(form==='quadruped'||form==='bird')for(const side of ['left','right']){
   const left=side==='left'
   if(body.parts[side+'Arm'])body.parts[side+'Arm']={...body.parts[side+'Arm'],label:(left?'Левая':'Правая')+(form==='bird'?' часть крыла':' передняя конечность'),group:form==='bird'?'other':left?'leftLeg':'rightLeg'}
   if(body.parts[side+'Hand'])body.parts[side+'Hand']={...body.parts[side+'Hand'],label:(left?'Левая':'Правая')+(form==='bird'?' оконечность крыла':' передняя лапа'),group:form==='bird'?'other':left?'leftLeg':'rightLeg'}
  }
  body.anatomy=createDetailedAnatomy(form,Object.keys(body.parts),wingStyle)
  if(!isDetailedAnatomy(body.anatomy,Object.keys(body.parts))){setMessage('Для этого тела получилось больше 512 структур. Уменьши число областей или используй текущую анатомию.');return}
  if(form==='bird')for(const s of body.anatomy.structures)if(/Arm|Hand/.test(s.region)&&s.functionGroup)s.functionGroup=s.region.startsWith('left')?'leftWing':'rightWing'
  if(form==='quadruped')for(const s of body.anatomy.structures)if(s.functionGroup==='leftHand'||s.functionGroup==='rightHand')s.functionGroup=s.functionGroup==='leftHand'?'leftLeg':'rightLeg'
  commit({...actor,body},'Подробная анатомия подключена; условные коэффициенты можно изменить.')
 }
 function correction(patch:Partial<AnatomyStructure>,text:string){
  if(!anatomy||!selected)return
  if(!reason.trim()){setMessage('Укажи причину коррекции мастера.');return}
  const next={...selected,...patch};if(!isStructure(next)){setMessage('Проверь структуру и численные параметры.');return}
  const a=copyDetailedAnatomy(anatomy)
  if(next.current<selected.current||next.injuries.some(i=>i.blocksUse&&!selected.injuries.some(old=>old.id===i.id)))a.harmRevision++
  a.structures=a.structures.map(s=>s.id===next.id?next:s)
  const log={id:crypto.randomUUID(),seconds,text:selected.name+': '+text,details:reason.trim()}
  commit({...actor,body:{...actor.body,anatomy:a},rpg:{...actor.rpg,logs:[...actor.rpg.logs,log].slice(-200)}},'Коррекция записана в историю.',false)
 }
 return <section className="w6-anatomy-panel"><div className="w6-section-heading"><div><p className="w6-eyebrow">Анатомический атлас</p><h3>Тело персонажа</h3><p className="w6-copy">Выбери область, переключи слой и осмотри отдельную структуру. Цвет показывает целостность; травма сохраняется после восстановления HP.</p></div><span className={'w6-life-badge'+(actor.rpg.dead?' w6-life-dead':'')}><StateIcon kind={actor.rpg.dead?'critical':actor.body.consciousness==='unconscious'?'shadow':'health'}/>{actor.rpg.dead?'Погиб':actor.body.consciousness==='unconscious'?'Без сознания':status.label}</span></div>
 <label className="w6-field"><span>Покров крыльев нового шаблона</span><select aria-label="Покров крыльев нового шаблона" value={wingStyle} onChange={e=>setWingStyle(e.currentTarget.value as 'membrane'|'feathers')}><option value="membrane">Перепончатые</option><option value="feathers">Перистые</option></select></label>
 <div className="w6-buttons"><button className={'w6-button'+(!playerView?' w6-active':'')} type="button" onClick={()=>setPlayerView(false)}>Полный осмотр мастера</button><button className={'w6-button'+(playerView?' w6-active':'')} type="button" onClick={()=>setPlayerView(true)}>Известное персонажу</button></div>
 {playerView&&<p className="w6-copy">Показываются наружные ткани и диагностированные травмы. Это локальная проекция листа; сетевые права доступа здесь ещё не настроены.</p>}
 <div className="w6-summary-bar"><span>Полёт: {bodyConsequences(actor.body).canFly?'доступен':'недоступен'}</span>{!playerView&&<span>Доступная мощность крыльев: {Math.round(bodyConsequences(actor.body).flightFactor*100)}%</span>}</div><div className="w6-anatomy-layout"><AnatomyAtlas body={actor.body} selectedRegion={selectedRegion} selectedStructure={structureId} inventory={actor.rpg.inventory} playerView={playerView} onLayer={kind=>{setFilter(['body','armor'].includes(kind)?'':kind);const next=anatomy?.structures.find(s=>s.region===selectedRegion&&s.kind===kind);if(next)setStructure(next.id)}} onSelectRegion={r=>{setRegion(r);setEditing(null)}} onSelectStructure={id=>{setStructure(id);setEditing(null)}}/>
 <aside className="w6-anatomy-detail"><h4>{selected&&selected.region===selectedRegion?selected.name:regions.find(r=>r.key===selectedRegion)?.label}</h4>{selected&&selected.region===selectedRegion&&(!playerView||selected.kind==='skin'||selected.injuries.some(i=>i.diagnosed))?<><div className="w6-structure-portrait"><StructureIllustration body={actor.body} structure={selected}/></div>{!playerView&&<><p className="w6-resource-total">Целостность {selected.current} / {selected.maximum}</p><div className="w6-meter"><i style={{width:selected.current/selected.maximum*100+'%'}}/></div></>}<p>{structureBlocked(selected)?'Функция утрачена':selected.current<selected.maximum?'Функция ограничена':'Функция сохранена'} · {kindLabels[selected.kind]}</p>{selected.connections&&<div className="w6-fieldset"><h4>Соединённые структуры</h4><div className="w6-buttons">{selected.connections.map(id=><button type="button" key={id} className="w6-button" onClick={()=>{const next=anatomy?.structures.find(s=>s.id===id);if(next){setRegion(next.region);setStructure(id)}}}>{anatomy?.structures.find(s=>s.id===id)?.name??id}</button>)}</div></div>}<p className="w6-copy">{selected.functionGroup?'Влияет на: '+({leftHand:'левую руку',rightHand:'правую руку',leftLeg:'левую ногу',rightLeg:'правую ногу',flight:'полёт',leftWing:'левое крыло и полёт',rightWing:'правое крыло и полёт'}[selected.functionGroup]??selected.functionGroup):'Не блокирует группу конечностей.'}</p>{selected.injuries.length?selected.injuries.filter(i=>!playerView||i.diagnosed).map(i=><div className="w6-injury" key={i.id}><StateIcon kind={selected.kind==='bone'?'fracture':'bleeding'}/><strong>{i.label}</strong><span>{i.diagnosed?'Диагноз известен':'Ещё не диагностировано'}</span>{!playerView&&<div className="w6-buttons"><button className="w6-button" type="button" disabled={i.diagnosed} onClick={()=>correction({injuries:selected.injuries.map(x=>x.id===i.id?{...x,diagnosed:true}:x)},'диагноз установлен')}>Установить диагноз</button><button className="w6-button w6-restore" type="button" onClick={()=>correction({injuries:selected.injuries.filter(x=>x.id!==i.id)},'снята травма '+i.label)}>Снять эту травму</button></div>}</div>):<p className="w6-copy">Отдельных травм нет.</p>}{!playerView&&<><button className="w6-button" type="button" onClick={()=>setEditing(structuredClone(selected))}>Настроить структуру</button><button className="w6-button w6-restore" type="button" onClick={()=>correction({current:selected.maximum},'целостность восстановлена без снятия травм')}>Восстановить целостность</button></>}</>:<p className="w6-copy">Выбери структуру на слое или в списке ниже.</p>}
 <h4>Структуры области ({visible.length})</h4><TextField label="Поиск структур области" value={query} onChange={setQuery}/><Field label="Тип структуры"><select value={filter} onChange={e=>setFilter(e.currentTarget.value)}><option value="">Все структуры</option>{Object.entries(kindLabels).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></Field><Check label="Только повреждённые структуры" value={damagedOnly} onChange={setDamagedOnly}/><div className="w6-structure-list">{visible.map(s=><button type="button" className={'w6-structure-row'+(s.id===structureId?' w6-active':'')} key={s.id} aria-pressed={s.id===structureId} onClick={()=>{setStructure(s.id);setEditing(null)}}><span>{s.name}</span><strong>{s.current}/{s.maximum}</strong>{s.injuries.length>0&&<StateIcon kind={s.kind==='bone'?'fracture':'bleeding'}/>}</button>)}</div>
 </aside></div>
 {!playerView&&<><label className="w6-field w6-spaced"><span>Причина решения / коррекции мастера</span><textarea rows={2} maxLength={1000} value={reason} onChange={e=>setReason(e.currentTarget.value)} placeholder="Осмотр, лечение, особенность расы или сюжетное решение"/></label>
 {editing&&<form className="w6-fieldset w6-form" onSubmit={e=>{e.preventDefault();correction(editing,'изменены параметры структуры');if(reason.trim()&&isStructure(editing))setEditing(null)}}><h4>Настройка: {editing.name}</h4><TextField label="Название структуры" value={editing.name} onChange={name=>setEditing({...editing,name})}/><div className="w6-attribute-grid"><NumberField label="Целостность структуры" value={editing.current} onChange={current=>setEditing({...editing,current})}/><NumberField label="Максимум структуры" value={editing.maximum} onChange={maximum=>setEditing({...editing,maximum})}/><NumberField label="Порог структуры (Дж)" value={editing.thresholdJ} onChange={thresholdJ=>setEditing({...editing,thresholdJ})}/><NumberField label="Энергия на HP структуры (Дж)" value={editing.joulesPerHp} onChange={joulesPerHp=>setEditing({...editing,joulesPerHp})}/><NumberField label="Передача энергии структуры (0–1)" max={1} value={editing.transmission} onChange={transmission=>setEditing({...editing,transmission})}/><NumberField label="Базовая кровопотеря структуры (мл/с)" value={editing.bleedingRate} onChange={bleedingRate=>setEditing({...editing,bleedingRate})}/><NumberField label="Снижение скорости группы при повреждении (%)" max={100} value={editing.slowdown??15} onChange={slowdown=>setEditing({...editing,slowdown})}/><NumberField label="Глубина от передней поверхности (0–1)" max={1} value={editing.depth} onChange={depth=>setEditing({...editing,depth})}/></div><Field label="Жизненно важная функция"><select value={editing.role} onChange={e=>setEditing({...editing,role:e.currentTarget.value as AnatomyStructure['role']})}><option value="none">Нет автоматической летальности</option><option value="brain">Сознание / мозг</option><option value="circulation">Кровообращение</option><option value="respiration">Дыхание</option><option value="core">Магическое ядро</option></select></Field><Field label="Группа блокируемой функции"><select value={editing.functionGroup} onChange={e=>setEditing({...editing,functionGroup:e.currentTarget.value})}>{Object.entries({'':'Без группы',leftHand:'Левая рука',rightHand:'Правая рука',leftLeg:'Левая нога',rightLeg:'Правая нога',leftWing:'Левое крыло',rightWing:'Правое крыло',flight:'Полёт',speech:'Речь'}).map(([k,label])=><option value={k} key={k}>{label}</option>)}</select></Field><button type="submit" className="w6-button w6-primary">Применить структуру</button><button type="button" className="w6-button" onClick={()=>setEditing(null)}>Отмена</button></form>}
 {selected&&anatomy&&<form className="w6-fieldset w6-form" onSubmit={e=>{e.preventDefault();if(!injury.trim()||selected.injuries.length>=20){setMessage('Укажи травму; максимум 20 травм структуры.');return}correction({injuries:[...selected.injuries,{id:crypto.randomUUID(),label:injury.trim(),blocksUse:true,diagnosed:true}]},'добавлена травма '+injury.trim());if(reason.trim())setInjury('')}}><h4>Добавить отдельную травму: {selected.name}</h4><TextField label="Травма структуры" value={injury} onChange={setInjury}/><p className="w6-copy">Эта травма блокирует функцию до отдельного лечения или коррекции мастера.</p><button type="submit" className="w6-button">Добавить травму структуры</button></form>}
 <details className="w6-fieldset" open={!anatomy}><summary>Форма тела и автоматические правила</summary><button type="button" className="w6-button" onClick={()=>setForm(inferAnatomyForm(actor.rpg.physiology.race+' '+actor.profile.origin,Object.keys(actor.body.parts)))}>Определить форму по профилю</button><Field label="Форма подробного тела"><select value={form} onChange={e=>setForm(e.currentTarget.value as AnatomyForm)}>{Object.entries(anatomyForms).map(([k,label])=><option key={k} value={k}>{label}</option>)}</select></Field><button className="w6-button w6-primary" type="button" onClick={connect}>{anatomy?'Заменить подробную анатомию':'Подключить подробную анатомию'}</button><p className="w6-copy">Четвероногое и птица используют общую игровую схему органов и адаптированную проекцию. Это начальные профили: особенности конкретного вида задаются настройками. HP областей и физиология не заменяются.</p>
 {anatomy&&<><div className="w6-buttons"><button type="button" className="w6-button" onClick={()=>addFeature('horns')}>Добавить рога</button><button type="button" className="w6-button" onClick={()=>addFeature('tail')}>Добавить хвост</button><button type="button" className="w6-button" onClick={()=>addFeature('arms')}>Добавить две руки</button></div><p>{anatomy.structures.length} отдельных структур · {anatomyForms[anatomy.form]}</p><Check label="Автоматически определять сознание и смерть" value={anatomy.automatic} onChange={automatic=>commit({...actor,body:{...actor.body,anatomy:{...copyDetailedAnatomy(anatomy),automatic}}},'Автоматические правила изменены.')}/><div className="w6-attribute-grid"><NumberField label="Дефицит для потери сознания (0–1)" max={1} value={lifeSettings?.unconsciousDeficit??anatomy.unconsciousDeficit} onChange={unconsciousDeficit=>setLifeSettings({...lifeSettings??{unconsciousDeficit:anatomy.unconsciousDeficit,lethalDeficit:anatomy.lethalDeficit},unconsciousDeficit})}/><NumberField label="Летальный дефицит (0–1)" max={1} value={lifeSettings?.lethalDeficit??anatomy.lethalDeficit} onChange={lethalDeficit=>setLifeSettings({...lifeSettings??{unconsciousDeficit:anatomy.unconsciousDeficit,lethalDeficit:anatomy.lethalDeficit},lethalDeficit})}/></div><button type="button" className="w6-button" disabled={!lifeSettings} onClick={()=>{if(!lifeSettings)return;const a={...copyDetailedAnatomy(anatomy),...lifeSettings};if(!isDetailedAnatomy(a)){setMessage('Пороги должны быть от 0 до 1, летальный — выше порога потери сознания.');return}commit({...actor,body:{...actor.body,anatomy:a}},'Пороги применены.');setLifeSettings(null)}}>Применить пороги состояния</button><p className="w6-copy">В одной жизненно важной группе смерть определяется при нулевой целостности всех её органов. Например, повреждение одного из двух лёгких не означает смерть. Мозг ниже 25% вызывает потерю сознания. Дефицит учитывает Ману/Тень и временное замещение; историческая сумма потерь не используется. Все пороги — игровые настройки.</p><button type="button" className="w6-button" onClick={()=>{const body=cloneBody(actor.body);for(const p of Object.values(body.parts))if(p.present&&!p.maximum){p.maximum=100;p.current=100}const impact={...actor.rpg.impact};for(const key of Object.keys(body.parts))if(!impact[key])impact[key]={thresholdJ:5,joulesPerHp:5,referenceCm2:10};commit({...actor,body,rpg:{...actor.rpg,impact}},'Для ненастроенных областей назначены учебные 100 HP и калибровка 5 Дж/HP.')}}>Назначить учебные HP и калибровку пустым областям</button></>}
 </details><div className="w6-fieldset"><h4>Решение мастера о состоянии</h4>{life?.reasons.map(r=><p className="w6-error" key={r}>{r}</p>)}{anatomy?.override&&<p className="w6-notice">Действует решение мастера: {anatomy.override.reason}</p>}<Field label="Состояние по решению мастера"><select value={state} onChange={e=>setState(e.currentTarget.value as typeof state)}><option value="unconscious">Жив, без сознания</option><option value="awake">Жив, в сознании</option><option value="dead">Погиб</option></select></Field><button className="w6-button w6-primary" type="button" onClick={()=>{try{onChange(masterLifeOverride(actor,seconds,state,reason,crypto.randomUUID()));setMessage('Решение мастера записано. Травмы сохранены. Сохрани изменения.')}catch(e){setMessage((e as Error).message)}}}>{actor.rpg.dead?'Отменить смерть / применить решение':'Применить решение мастера'}</button></div>
 {anatomy?.lastTrace&&<details className="w6-fieldset" open><summary>Последний внутренний путь попадания</summary><p>{anatomy.lastTrace.initialJ.toFixed(2)} Дж после брони → {anatomy.lastTrace.remainingJ.toFixed(2)} Дж остатка · {anatomy.lastTrace.point.approach==='front'?'спереди':'сзади'} · {anatomy.lastTrace.point.mechanism}</p><HitPath trace={anatomy.lastTrace} onSelect={id=>{const s=anatomy.structures.find(s=>s.id===id);if(s){setRegion(s.region);setStructure(id);setEditing(null)}}}/><div className="w6-table-wrap"><table className="w6-trace-table"><thead><tr><th>Структура</th><th>До, Дж</th><th>После, Дж</th><th>Урон</th></tr></thead><tbody>{anatomy.lastTrace.steps.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.beforeJ.toFixed(2)}</td><td>{s.afterJ.toFixed(2)}</td><td>{s.damage} HP</td></tr>)}</tbody></table></div></details>}
 <details className="w6-fieldset"><summary>История состояния и решений мастера</summary>{actor.rpg.logs.slice().reverse().slice(0,50).map(l=><article className="w6-entry" key={l.id}><strong>{l.seconds} с · {l.text}</strong><p className="w6-prose">{l.details}</p></article>)}</details></>}
 <p className="w6-notice" role="status">{message}</p></section>
}
