import { useState } from 'react'
import type { World, PlanResult } from './rpgEngine'
import { advanceWorld, worldFingerprint, effectiveActor } from './rpgEngine'
import { NumberField, Field, TextField } from './RpgControls'
import { downloadJson, MAX_IMPORT_BYTES, portableCharacter } from './characterTransfer'
import { isCampaign, copyCampaign } from './rpgSchema'
import { assertCampaignSize } from './campaignLimits'
import { sceneReferencesValid } from './scenes'
import { isSavedCharacter } from './characterModel'
import type { SavedCharacter } from './characterModel'
type Props={world:World;onPlan:(p:PlanResult)=>void;onRestore:(w:World)=>{ok:boolean;message:string};onExamples:()=>{ok:boolean;message:string};remote?:boolean}
export default function CampaignPanel({world,onPlan,onRestore,onExamples,remote}:Props){
 const [correctionTarget,setCorrectionTarget]=useState(world.characters[0]?.id??''),[correctionKey,setCorrectionKey]=useState('blood'),[correctionRegion,setCorrectionRegion]=useState('torso'),[correctionValue,setCorrectionValue]=useState(0),[reason,setReason]=useState('')
 const [seconds,setSeconds]=useState(1),[message,setMessage]=useState(''),[restore,setRestore]=useState<World|null>(null)
 function preview(){try{const id=crypto.randomUUID(),next=advanceWorld(world,seconds,id),last=next.campaign.logs.at(-1)!;onPlan({ok:true,plan:{world:next,fingerprint:worldFingerprint(world),text:last.text,details:last.details,eventId:id}})}catch(e){onPlan({ok:false,message:(e as Error).message})}}
 function backup(){try{if(!isCampaign(world.campaign)||!world.characters.every(isSavedCharacter))throw new Error('Исправь незавершённые поля перед экспортом кампании.');assertCampaignSize(world);const text=JSON.stringify({format:'world6-campaign-backup',version:1,exportedAt:new Date().toISOString(),characters:world.characters.map(c=>({...portableCharacter(c),id:c.id})),campaign:copyCampaign(world.campaign)});if(new TextEncoder().encode(text).byteLength>MAX_IMPORT_BYTES){setMessage('Копия больше 10 МиБ. Экспортируй отдельных героев и уменьши каталог.');return}downloadJson(text,'world6-campaign-'+new Date().toISOString().slice(0,10)+'.json');setMessage('Создана копия текущих листов, каталогов, сцен и часов.')}catch(e){setMessage((e as Error).message)}}
 function correction(){
  try{
    if(!reason.trim()||reason.length>1000||!Number.isFinite(correctionValue)||correctionValue<0)throw new Error('Укажи причину коррекции и допустимое значение.')
    const next:World={characters:world.characters.map(c=>({...portableCharacter(c),id:c.id})),campaign:copyCampaign(world.campaign)},actor=next.characters.find(c=>c.id===correctionTarget)
    if(!actor)throw new Error('Выбери героя для коррекции.')
    let before:number
    if(correctionKey==='blood'){before=actor.rpg.physiology.currentMl;if(correctionValue>actor.rpg.physiology.normalMl)throw new Error('Объём выше нормального.');actor.rpg.physiology.currentMl=correctionValue}
    else if(correctionKey==='local'){const p=actor.body.parts[correctionRegion];if(!p||!p.present||!Number.isInteger(correctionValue)||correctionValue>p.maximum)throw new Error('Проверь область и целое локальное HP.');before=p.current;p.current=correctionValue}
    else {const key=correctionKey as 'health'|'mana'|'shadow'|'stamina';before=Number(actor.resources[key].current);if(correctionValue>Number(effectiveActor(actor,next.campaign.seconds).resources[key].maximum))throw new Error('Значение выше действующего максимума.');actor.resources[key].current=String(correctionValue)}
    const id=crypto.randomUUID(),text='Коррекция мастера: '+actor.name,details=correctionKey+(correctionKey==='local'?' / '+correctionRegion:'')+': '+before+' → '+correctionValue+'. Основание: '+reason.trim()
    const log={id,seconds:next.campaign.seconds,text,details};next.campaign.logs=[...next.campaign.logs,log].slice(-200);actor.rpg.logs=[...actor.rpg.logs,log].slice(-200);next.campaign.revision++
    onPlan({ok:true,plan:{fingerprint:worldFingerprint(world),world:next,text,details,eventId:id}})
  }catch(e){setMessage((e as Error).message)}
 }
 async function read(file:File|undefined){setRestore(null);if(!file)return;if(file.size>MAX_IMPORT_BYTES){setMessage('Максимум 10 МиБ.');return}try{const x:unknown=JSON.parse(await file.text());if(typeof x!=='object'||x===null)throw new Error('Неверный файл.');const p=x as Record<string,unknown>;if(p.format!=='world6-campaign-backup'||p.version!==1||!isCampaign(p.campaign)||!Array.isArray(p.characters)||p.characters.length>200||!p.characters.every(isSavedCharacter)||new Set(p.characters.map(c=>c.id)).size!==p.characters.length)throw new Error('Нужна корректная полная копия кампании.');const chars=(p.characters as SavedCharacter[]).map(c=>({...portableCharacter(c),id:c.id}));const ids=new Set(chars.map(c=>c.id));if(!sceneReferencesValid((p.campaign as World['campaign']).scenes,[...ids]))throw new Error('В копии сцены с неизвестными героями.');if(chars.some(c=>c.rpg.casts.some(k=>['preparing','ready','maintaining'].includes(k.status)&&!ids.has(k.targetId))))throw new Error('В копии не хватает целей незавершённых применений.');if(chars.some(c=>c.rpg.effects.some(e=>e.ownerId&&(!ids.has(e.ownerId)||!chars.find(x=>x.id===e.ownerId)?.rpg.casts.some(k=>k.id===e.castId)))))throw new Error('В копии не хватает источников поддерживаемых эффектов.');setRestore({characters:chars,campaign:copyCampaign(p.campaign)});setMessage('Проверь состав перед заменой текущей кампании.')}catch(e){setMessage((e as Error).message)}}
 return <section className="panel w6-campaign"><h2>Кампания · {world.campaign.seconds} с</h2><p className="w6-copy">Общие часы для всех героев. При продвижении учитываются кровопотеря, восполнение, подготовка, длительности и расход поддержания.</p><div className="w6-time-controls"><NumberField label="Продвинуть время (с)" value={seconds} onChange={setSeconds}/><button className="w6-button w6-primary" type="button" onClick={preview}>Предварительный расчёт времени</button></div>
 <details className="w6-fieldset"><summary>Полная копия и восстановление</summary><p className="w6-copy">Полная копия включает текущие листы, общий каталог, сцены и часы. Обычный импорт отдельного героя создаёт копию и не заменяет кампанию.</p><button className="w6-button" type="button" onClick={backup}>Экспорт всей кампании</button>{remote?<p className="w6-copy">Для восстановления лобби используй «Копия лобби и восстановление владельцев» выше. Эта кнопка экспортирует текущий черновик.</p>:<><label className="w6-field w6-spaced"><span>Выбрать полную копию для восстановления</span><input type="file" accept=".json,application/json" onChange={e=>void read(e.currentTarget.files?.[0])}/></label>{restore&&<div className="w6-entry"><p>Героев: {restore.characters.length}; время: {restore.campaign.seconds} с; шаблонов предметов: {restore.campaign.items.length}; способностей: {restore.campaign.abilities.length}.</p><p>{restore.characters.map(c=>c.name).join(', ')}</p><button className="w6-button w6-danger" type="button" onClick={()=>{if(window.confirm('Заменить текущую кампанию этой копией? Экспортируй текущую перед заменой.')){const r=onRestore(restore);setMessage(r.message);if(r.ok)setRestore(null)}}}>Восстановить с заменой текущей кампании</button></div>}</>}</details>
 <details className="w6-fieldset"><summary>Учебные примеры для проверки формул</summary><p className="w6-copy">Добавляются два отдельных учебных героя, камень и примеры мягкой/жёсткой защиты. Значения условные, для проверки цепочки расчёта; твои герои не изменяются.</p><button className="w6-button" type="button" onClick={()=>setMessage(onExamples().message)}>Добавить учебные примеры</button></details>
 <details className="w6-fieldset"><summary>Коррекция мастера отдельным событием</summary><div className="w6-attribute-grid"><Field label="Герой для коррекции"><select value={correctionTarget} onChange={e=>setCorrectionTarget(e.currentTarget.value)}><option value="">Выбери героя</option>{world.characters.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Исправляемое значение"><select value={correctionKey} onChange={e=>setCorrectionKey(e.currentTarget.value)}>{Object.entries({mana:'Мана',shadow:'Тень',stamina:'Выносливость',blood:'Объём крови',local:'Локальный HP'}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field>{correctionKey==='local'&&<Field label="Область для коррекции"><select value={correctionRegion} onChange={e=>setCorrectionRegion(e.currentTarget.value)}>{Object.entries(world.characters.find(c=>c.id===correctionTarget)?.body.parts??{}).map(([k,p])=><option key={k} value={k}>{p.label||k}</option>)}</select></Field>}<NumberField label="Исправленное текущее значение" value={correctionValue} onChange={setCorrectionValue}/></div><TextField label="Причина коррекции" max={1000} value={reason} onChange={setReason}/><button className="w6-button" type="button" onClick={correction}>Предварительная коррекция</button><p className="w6-copy">Прежнее событие не переписывается; новое значение и причина добавляются в историю.</p></details>
 <details className="w6-fieldset"><summary>Общая история ({world.campaign.logs.length})</summary>{world.campaign.logs.slice().reverse().map(l=><article className="w6-entry" key={l.id}><h4>{l.seconds} с · {l.text}</h4><p className="w6-prose">{l.details}</p></article>)}</details><p role="status" className="w6-notice">{message}</p></section>
}
