import { useState } from 'react'
import { useOnline } from './onlineContext'
import { useRemote } from './onlineHooks'
import { readCharacters,writeCharacters } from './characterStorage'
import { createCharacterArchive,downloadJson } from './characterTransfer'
import type { SavedCharacter } from './characterModel'
import type { CloudCharacter } from './onlineTypes'
import { RemoteStatus } from './NetworkCommon'
export default function CloudLibraryPanel({onImported}:{onImported:()=>void}){
 const {user,request,refresh}=useOnline(),list=useRemote<CloudCharacter[]>(user?'/characters':null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 if(!user)return <section className="panel"><p className="w6-copy">Локальные герои доступны без входа. В аккаунте можно хранить копии для других устройств и подключать их к лобби.</p></section>
 const key='world6.cloud-versions.'+user.id
 function versions():Record<string,number>{try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return {}}}
 function remember(characterId:string,revision:number){localStorage.setItem(key,JSON.stringify({...versions(),[characterId]:revision}))}
 function forget(characterId:string){const known=versions();delete known[characterId];localStorage.setItem(key,JSON.stringify(known))}
 async function act(fn:()=>Promise<string>){setBusy(true);try{setMessage(await fn());refresh()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 async function upload(){const local=readCharacters(localStorage);if(local.blocked)throw new Error(local.message);let saved=0,skipped=0;for(const c of local.characters){const known=versions()[c.id],exists=list.value?.some(r=>r.id===c.id);if(exists&&known===undefined){skipped++;continue}const result=await request<{revision:number}>('/characters/'+c.id,{method:'PUT',body:JSON.stringify({character:c,revision:known??-1})});remember(c.id,result.revision);saved++}return `Сохранено в аккаунт: ${saved}. ${skipped?'Для '+skipped+' героев сначала загрузи копию из аккаунта, чтобы проверить её версию.':''}`}
 return <section className="panel w6-cloud-library"><details><summary>Герои в аккаунте · {list.value?.length??0}</summary><p className="w6-copy">Загрузка в аккаунт сохраняет локальные листы после нажатия кнопки. Герой в лобби — отдельная копия, состояние которой ведёт мастер.</p><div className="w6-buttons"><button className="w6-button w6-primary" disabled={busy||!list.value} onClick={()=>void act(upload)}>Сохранить локальных героев в аккаунт</button><button className="w6-button" onClick={refresh}>Обновить список аккаунта</button></div><RemoteStatus error={list.error} loading={list.loading}/><div className="w6-character-list">{list.value?.map(c=><article className="w6-character-card" key={c.id}><h3>{c.name}</h3><small>Версия {c.revision+1}</small><div className="w6-buttons"><button className="w6-button" disabled={busy} onClick={()=>void act(async()=>{const remote=await request<{character:SavedCharacter;revision:number}>('/characters/'+c.id),local=readCharacters(localStorage);if(local.blocked)throw new Error(local.message);if(local.characters.some(x=>x.id===c.id)&&!window.confirm('Заменить локальный лист свежей копией аккаунта?'))return 'Загрузка отменена.';writeCharacters(localStorage,[...local.characters.filter(x=>x.id!==c.id),remote.character],local.campaign);remember(c.id,remote.revision);onImported();return 'Герой загружен из аккаунта.'})}>Загрузить в редактор</button><button className="w6-button" disabled={busy} onClick={()=>void act(async()=>{const remote=await request<{character:SavedCharacter}>('/characters/'+c.id);downloadJson(createCharacterArchive([remote.character],new Date().toISOString()),'world6-cloud-character.json');return 'Экспорт подготовлен.'})}>Скачать JSON</button><button className="w6-button w6-danger" disabled={busy} onClick={()=>{if(window.confirm('Удалить героя из аккаунта? Копии в лобби сохранятся.'))void act(async()=>{await request('/characters/'+c.id,{method:'DELETE'});forget(c.id);return 'Герой удалён из аккаунта.'})}}>Удалить из аккаунта</button></div></article>)}</div><p className="w6-notice" role="status">{message}</p></details></section>
}
