import { useState } from 'react'
import { useOnline } from './onlineContext'
import { useRemote,useDebounced } from './onlineHooks'
import type { Feed,Topic,Post } from './onlineTypes'
import { CommunityShell,RemoteStatus,formatDate } from './NetworkCommon'
import { TextField,Field } from './RpgControls'
export default function ForumPanel({onAccount}:{onAccount:()=>void}){
 const {user,request,refresh}=useOnline(),[query,setQuery]=useState(''),[category,setCategory]=useState(''),[offset,setOffset]=useState(0),[opened,setOpened]=useState(''),[replyOffset,setReplyOffset]=useState(0),[title,setTitle]=useState(''),[body,setBody]=useState(''),[newCategory,setNewCategory]=useState('general'),[reply,setReply]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 const q=useDebounced(query),categories=useRemote<{id:string;name:string}[]>('/forum/categories'),feed=useRemote<Feed<Topic>>('/forum/topics?q='+encodeURIComponent(q)+'&category='+category+'&offset='+offset),thread=useRemote<{topic:Topic;replies:Post[];hasMore:boolean}>(opened?'/forum/topics/'+opened+'?offset='+replyOffset:null)
 const moderator=!!user&&['ADMIN','OWNER'].includes(user.role)
 async function act(fn:()=>Promise<void>){setBusy(true);try{await fn();refresh();setMessage('Изменение опубликовано.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <CommunityShell title="Форум"><p className="w6-copy">Общие темы и ответы участников Мира 6. Читать можно без входа; публикации доступны из аккаунта.</p>
 <div className="w6-community-tools"><TextField label="Поиск тем" value={query} onChange={v=>{setQuery(v);setOffset(0)}}/><Field label="Раздел форума"><select aria-label="Раздел форума" value={category} onChange={e=>{setCategory(e.currentTarget.value);setOffset(0)}}><option value="">Все разделы</option>{categories.value?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><button className="w6-button" onClick={refresh}>Обновить темы</button></div>
 {!user?<button className="w6-button" onClick={onAccount}>Войти, чтобы создать тему</button>:<details className="w6-fieldset"><summary>Создать тему</summary><form className="w6-form" onSubmit={e=>{e.preventDefault();void act(async()=>{const result=await request<{id:string}>('/forum/topics',{method:'POST',body:JSON.stringify({title,body,category:newCategory})});setTitle('');setBody('');setOpened(result.id);setReplyOffset(0)})}}><TextField label="Название темы" value={title} onChange={setTitle}/><Field label="Раздел новой темы"><select aria-label="Раздел новой темы" value={newCategory} onChange={e=>setNewCategory(e.currentTarget.value)}>{categories.value?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><label className="w6-field"><span>Текст темы</span><textarea required maxLength={8000} rows={5} value={body} onChange={e=>setBody(e.currentTarget.value)}/></label><button className="w6-button w6-primary" disabled={busy||!title.trim()||!body.trim()}>Опубликовать тему</button></form></details>}
 <RemoteStatus error={feed.error} loading={feed.loading}/><div className="w6-topic-list">{feed.value?.items.map(t=><button className={'w6-topic-row'+(opened===t.id?' w6-topic-selected':'')} key={t.id} onClick={()=>{setOpened(t.id);setReplyOffset(0);setReply('')}}><span><small>{categories.value?.find(c=>c.id===t.category)?.name}{!!t.pinned?' · Закреплена':''}{!!t.locked?' · Закрыта':''}</small><strong>{t.title}</strong><small>{t.author} · {formatDate(t.updated_at)}</small></span><span className="w6-topic-count">{t.replies}<small>ответов</small></span></button>)}</div>{feed.value?.items.length===0&&<p className="w6-empty">Тем пока нет. Начни обсуждение.</p>}<div className="w6-buttons">{offset>0&&<button className="w6-button" onClick={()=>setOffset(Math.max(0,offset-20))}>Предыдущие темы</button>}{feed.value?.hasMore&&<button className="w6-button" onClick={()=>setOffset(offset+20)}>Следующие темы</button>}</div>
 {opened&&<div className="w6-thread"><RemoteStatus error={thread.error} loading={thread.loading}/>{thread.value&&<><article className="w6-thread-original"><small>{thread.value.topic.author} · {formatDate(thread.value.topic.created_at)}</small><h2>{thread.value.topic.title}</h2><p className="w6-prose">{thread.value.topic.body}</p><div className="w6-buttons">{moderator&&<><button className="w6-button" disabled={busy} onClick={()=>void act(async()=>{await request('/forum/topics/'+opened,{method:'PATCH',body:JSON.stringify({locked:!thread.value!.topic.locked,pinned:!!thread.value!.topic.pinned})})})}>{thread.value.topic.locked?'Открыть ответы':'Закрыть ответы'}</button><button className="w6-button" disabled={busy} onClick={()=>void act(async()=>{await request('/forum/topics/'+opened,{method:'PATCH',body:JSON.stringify({locked:!!thread.value!.topic.locked,pinned:!thread.value!.topic.pinned})})})}>{thread.value.topic.pinned?'Открепить':'Закрепить'}</button></>}{(moderator||user?.id===thread.value.topic.author_id)&&<button className="w6-button w6-danger" disabled={busy} onClick={()=>{if(window.confirm('Удалить тему из общего форума?'))void act(async()=>{await request('/forum/topics/'+opened,{method:'DELETE'});setOpened('')})}}>Удалить тему</button>}</div></article>
 {thread.value.replies.map(p=><article className="w6-forum-post" key={p.id}><small>{p.author} · {formatDate(p.created_at)}</small><p className="w6-prose">{p.body}</p>{(moderator||user?.id===p.author_id)&&<button className="w6-button" disabled={busy} onClick={()=>{if(window.confirm('Удалить ответ?'))void act(async()=>{await request('/forum/replies/'+p.id,{method:'DELETE'})})}}>Удалить ответ</button>}</article>)}<div className="w6-buttons">{replyOffset>0&&<button className="w6-button" onClick={()=>setReplyOffset(Math.max(0,replyOffset-50))}>Предыдущие ответы</button>}{thread.value.hasMore&&<button className="w6-button" onClick={()=>setReplyOffset(replyOffset+50)}>Следующие ответы</button>}</div>
 {user&&!thread.value.topic.locked?<form className="w6-form" onSubmit={e=>{e.preventDefault();void act(async()=>{await request('/forum/topics/'+opened+'/replies',{method:'POST',body:JSON.stringify({body:reply})});setReply('')})}}><label className="w6-field"><span>Твой ответ</span><textarea required rows={4} maxLength={8000} value={reply} onChange={e=>setReply(e.currentTarget.value)}/></label><button className="w6-button w6-primary" disabled={busy||!reply.trim()}>Опубликовать ответ</button></form>:<p>{thread.value.topic.locked?'Ответы закрыты модератором.':'Войди в аккаунт, чтобы ответить.'}</p>}</>}</div>}
 <p className="w6-notice" role="status">{message}</p></CommunityShell>
}
