import { lazy,Suspense,useEffect,useState } from 'react'
import { useOnline } from './onlineContext'
import { useRemote,useDebounced } from './onlineHooks'
import type { CloudCharacter,Feed,LobbyCard,Lobby,MineLobby,Post,PlayerWorld } from './onlineTypes'
import type { World } from './rpgEngine'
import { CommunityShell,RemoteStatus,formatDate } from './NetworkCommon'
import { TextField,Field } from './RpgControls'
import { rankOptions } from './characterProfile'
const CharacterManager=lazy(()=>import('./CharacterManager'))
const rankName=(key:string)=>rankOptions.find(r=>r.key===key)?.label??key
const statusName=(status:string)=>({open:'Набор открыт',playing:'Игра идёт',closed:'Закрыто'})[status]??status
export default function LobbiesPanel({onAccount}:{onAccount:()=>void}){
 const {user,request,refresh,socket}=useOnline(),[query,setQuery]=useState(''),[genre,setGenre]=useState(''),[energy,setEnergy]=useState(''),[rank,setRank]=useState(''),[offset,setOffset]=useState(0),[opened,setOpened]=useState(''),[invite,setInvite]=useState(()=>new URLSearchParams(location.search).get('invite')||''),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[newGenre,setNewGenre]=useState('Приключение'),[slots,setSlots]=useState(4),[newEnergy,setNewEnergy]=useState('any'),[newRank,setNewRank]=useState('mortal'),[visibility,setVisibility]=useState('public'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[chat,setChat]=useState(''),[characterId,setCharacterId]=useState(''),[before,setBefore]=useState(''),[editor,setEditor]=useState<(World&{revision:number})|null>(null),[editorKey,setEditorKey]=useState(0)
 const q=useDebounced(query),feed=useRemote<Feed<LobbyCard>>('/lobbies?q='+encodeURIComponent(q)+'&genre='+encodeURIComponent(genre)+'&energy='+energy+'&rank='+rank+'&offset='+offset),mine=useRemote<MineLobby[]>(user?'/lobbies/mine':null),lobby=useRemote<Lobby>(user&&opened?'/lobbies/'+opened:null),messages=useRemote<Feed<Post>>(user&&opened?'/lobbies/'+opened+'/messages'+(before?'?before='+encodeURIComponent(before):''):null),cloud=useRemote<CloudCharacter[]>(user?'/characters':null),state=useRemote<PlayerWorld>(user&&opened?'/lobbies/'+opened+'/world?view=player':null)
 useEffect(()=>{if(!socket||!opened)return;const subscribe=()=>socket.emit('subscribeLobby',opened,()=>{});if(socket.connected)subscribe();socket.on('connect',subscribe);return()=>{socket.off('connect',subscribe);socket.emit('unsubscribeLobby',opened)}},[socket,opened])
 useEffect(()=>{setEditor(null);setBefore('')},[opened,user?.id])
 async function act(fn:()=>Promise<string|void>){setBusy(true);try{setMessage(await fn()||'Изменение сохранено.');refresh()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 function open(lobbyId:string){setOpened(lobbyId);setChat('');setCharacterId('')}
 async function loadEditor(){const remote=await request<World&{revision:number}>('/lobbies/'+opened+'/world');setEditor(remote);setEditorKey(k=>k+1);return 'Свежая кампания загружена в черновик мастера.'}
 return <CommunityShell title="Поиск лобби"><p className="w6-copy">Найди кампанию, вступи в неё и играй с другими участниками. Закрытые лобби доступны по приглашению.</p>
 <div className="w6-community-tools"><TextField label="Поиск лобби" value={query} onChange={v=>{setQuery(v);setOffset(0)}}/><Field label="Жанр лобби"><select aria-label="Жанр лобби" value={genre} onChange={e=>{setGenre(e.currentTarget.value);setOffset(0)}}><option value="">Любой жанр</option>{['Приключение','Исследование','Тайна','Свободная игра'].map(g=><option key={g}>{g}</option>)}</select></Field><Field label="Энергия лобби"><select aria-label="Энергия лобби" value={energy} onChange={e=>{setEnergy(e.currentTarget.value);setOffset(0)}}><option value="">Любая настройка</option><option value="any">Мана или Тень</option><option value="mana">Только Мана</option><option value="shadow">Только Тень</option></select></Field><Field label="Ранг лобби"><select aria-label="Ранг лобби" value={rank} onChange={e=>{setRank(e.currentTarget.value);setOffset(0)}}><option value="">Любой ранг</option>{rankOptions.map(r=><option key={r.key} value={r.key}>{r.label}</option>)}</select></Field></div><button className="w6-button" onClick={refresh}>Обновить лобби</button>
 {user?<><details className="w6-fieldset"><summary>Создать лобби</summary><form className="w6-form" onSubmit={e=>{e.preventDefault();void act(async()=>{const result=await request<{id:string}>('/lobbies',{method:'POST',body:JSON.stringify({title,description,genre:newGenre,slots,energy:newEnergy,rank:newRank,visibility})});setTitle('');setDescription('');open(result.id);return 'Лобби создано. Ты его мастер.'})}}><TextField label="Название лобби" value={title} onChange={setTitle}/><label className="w6-field"><span>Описание лобби</span><textarea required rows={4} maxLength={4000} value={description} onChange={e=>setDescription(e.currentTarget.value)}/></label><div className="w6-attribute-grid"><Field label="Жанр новой кампании"><select aria-label="Жанр новой кампании" value={newGenre} onChange={e=>setNewGenre(e.currentTarget.value)}>{['Приключение','Исследование','Тайна','Свободная игра'].map(g=><option key={g}>{g}</option>)}</select></Field><label className="w6-field"><span>Мест для игроков, кроме мастера</span><input required type="number" min={1} max={12} value={slots} onChange={e=>setSlots(Number(e.currentTarget.value))}/></label><Field label="Допустимая энергия"><select aria-label="Допустимая энергия" value={newEnergy} onChange={e=>setNewEnergy(e.currentTarget.value)}><option value="any">Мана или Тень</option><option value="mana">Только Мана</option><option value="shadow">Только Тень</option></select></Field><Field label="Стартовый ранг"><select aria-label="Стартовый ранг" value={newRank} onChange={e=>setNewRank(e.currentTarget.value)}>{rankOptions.map(r=><option key={r.key} value={r.key}>{r.label}</option>)}</select></Field><Field label="Видимость лобби"><select aria-label="Видимость лобби" value={visibility} onChange={e=>setVisibility(e.currentTarget.value)}><option value="public">В общем поиске</option><option value="private">По приглашению</option></select></Field></div><p className="w6-copy">Стартовый ранг обозначает условия кампании. Мастер проверяет и утверждает героев отдельно.</p><button className="w6-button w6-primary" disabled={busy||!title.trim()||!description.trim()}>Создать общую кампанию</button></form></details>
 <form className="w6-form w6-fieldset" onSubmit={e=>{e.preventDefault();void act(async()=>{const result=await request<{id:string}>('/lobbies/join',{method:'POST',body:JSON.stringify({code:invite})});open(result.id);return 'Ты вступил по приглашению.'})}}><TextField label="Код приглашения" value={invite} onChange={setInvite} max={64}/><button className="w6-button" disabled={busy||!invite.trim()}>Вступить по приглашению</button></form><h3>Мои лобби</h3><RemoteStatus error={mine.error} loading={mine.loading}/><div className="w6-buttons">{mine.value?.map(l=><button className={'w6-button'+(opened===l.id?' w6-active':'')} key={l.id} onClick={()=>open(l.id)}>{l.title} · {l.role==='GM'?'Мастер':'Игрок'}</button>)}</div></>:<button className="w6-button" onClick={onAccount}>Войти для участия или создания лобби</button>}
 <RemoteStatus error={feed.error} loading={feed.loading}/><div className="w6-race-cards">{feed.value?.items.map(l=><article className="w6-race-card" key={l.id}><small>{l.genre} · {statusName(l.status)}</small><h3>{l.title}</h3><p className="w6-prose">{l.description}</p><p>Мастер: {l.owner}. Игроков: {l.players} / {l.slots}.</p><p>{rankName(l.rank)} · {l.energy==='any'?'Мана или Тень':l.energy==='mana'?'Мана':'Тень'}</p><button className="w6-button w6-primary" disabled={busy} onClick={()=>{if(!user){onAccount();return}if(mine.value?.some(m=>m.id===l.id)){open(l.id);return}void act(async()=>{const result=await request<{id:string}>('/lobbies/'+l.id+'/join',{method:'POST'});open(result.id);return 'Ты вступил в лобби.'})}}>{mine.value?.some(m=>m.id===l.id)?'Открыть лобби':'Вступить в лобби'}</button></article>)}</div>{feed.value?.items.length===0&&<p className="w6-empty">Подходящих лобби пока нет.</p>}<div className="w6-buttons">{offset>0&&<button className="w6-button" onClick={()=>setOffset(offset-20)}>Предыдущие лобби</button>}{feed.value?.hasMore&&<button className="w6-button" onClick={()=>setOffset(offset+20)}>Следующие лобби</button>}</div>
 {user&&opened&&<section className="w6-lobby-room"><RemoteStatus error={lobby.error} loading={lobby.loading}/>{lobby.value&&<><header className="w6-section-heading"><div><p className="w6-eyebrow">{lobby.value.myRole==='GM'?'Стол мастера':'Общая кампания'}</p><h2>{lobby.value.title}</h2><p>{statusName(lobby.value.status)} · {lobby.value.visibility==='public'?'Открытое':'Закрытое'} лобби</p></div><button className="w6-button" onClick={()=>open('')}>Свернуть лобби</button></header>
 {lobby.value.myRole==='GM'&&<div className="w6-fieldset"><h3>Управление лобби</h3><Field label="Статус лобби"><select aria-label="Статус лобби" value={lobby.value.status} disabled={busy} onChange={e=>{const status=e.currentTarget.value;void act(async()=>{await request('/lobbies/'+opened,{method:'PATCH',body:JSON.stringify({status})})})}}><option value="open">Набор открыт</option><option value="playing">Игра идёт</option><option value="closed">Закрыто</option></select></Field><p>Код приглашения: <strong className="w6-break">{lobby.value.inviteCode}</strong></p><div className="w6-buttons"><button className="w6-button" onClick={()=>void act(async()=>{const url=new URL(location.href);url.searchParams.set('invite',lobby.value!.inviteCode!);await navigator.clipboard.writeText(url.href);return 'Ссылка приглашения скопирована.'})}>Скопировать приглашение</button><button className="w6-button" disabled={busy} onClick={()=>{if(window.confirm('Заменить код? Прежние приглашения перестанут работать.'))void act(async()=>{await request('/lobbies/'+opened+'/invite/rotate',{method:'POST'})})}}>Сменить код приглашения</button></div></div>}
 <div className="w6-lobby-columns"><div><h3>Участники</h3>{lobby.value.members.map(m=><div className="w6-member-row" key={m.id}><span>{m.displayName}<small>{m.lobbyRole==='GM'?'Мастер':'Игрок'}</small></span>{lobby.value!.myRole==='GM'&&m.lobbyRole!=='GM'&&<button className="w6-button" disabled={busy} onClick={()=>{if(window.confirm('Исключить игрока и убрать его героев из этой кампании?'))void act(async()=>{await request('/lobbies/'+opened+'/members/'+m.id,{method:'DELETE'})})}}>Исключить</button>}</div>)}{lobby.value.myRole!=='GM'&&<button className="w6-button w6-danger" disabled={busy} onClick={()=>{if(window.confirm('Выйти из лобби? Твои герои этой кампании будут убраны.'))void act(async()=>{await request('/lobbies/'+opened+'/members/'+user.id,{method:'DELETE'});open('');return 'Ты вышел из лобби.'})}}>Выйти из лобби</button>}
 <h3>Герои кампании</h3><RemoteStatus error={state.error} loading={state.loading}/>{state.value?.characters.map(c=><article className="w6-player-sheet" key={c.id}><h4>{c.name}</h4><p>{rankName(c.profile.rank)} · {c.profile.energy==='shadow'?'Тень':'Мана'}</p>{lobby.value!.myRole==='GM'?<button className="w6-button" disabled={busy} onClick={()=>void act(async()=>{await request('/lobbies/'+opened+'/characters/'+c.id,{method:'PATCH',body:JSON.stringify({approved:!c.approved})})})}>{c.approved?'Снять утверждение героя':'Утвердить героя'}</button>:<small>{c.approved?'Герой утверждён':'Ожидает проверки мастером'}</small>}{c.ownerId===user.id&&<>{c.resources&&<p>{Object.entries(c.resources).filter(([,r])=>Number(r.maximum)>0).map(([key,r])=><span key={key}>{key==='mana'?'Мана':key==='shadow'?'Тень':'Выносливость'}: {r.current} / {r.maximum} · </span>)}</p>}{c.sensations?.length?c.sensations.map((s,i)=><div key={i}><strong>{s.label}</strong>{s.symptoms.map(t=><p key={t}>{t}</p>)}{s.diagnoses.map(t=><p key={t}>Известный диагноз: {t}</p>)}</div>):c.resources&&<p>Заметных ранений не ощущается.</p>}{c.capabilities?.map(t=><p key={t}>{t}</p>)}{!!c.abilities?.length&&<details><summary>Известные способности</summary>{c.abilities.map(a=><p key={a.id}><strong>{a.name}</strong> · {a.description}</p>)}</details>}</>}</article>)}
 <form className="w6-form w6-fieldset" onSubmit={e=>{e.preventDefault();void act(async()=>{await request('/lobbies/'+opened+'/characters',{method:'POST',body:JSON.stringify({characterId})});setCharacterId('');return 'Герой добавлен как отдельная копия для проверки мастером.'})}}><Field label="Герой из аккаунта"><select aria-label="Герой из аккаунта" required value={characterId} onChange={e=>setCharacterId(e.currentTarget.value)}><option value="">Выбери героя</option>{cloud.value?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><p className="w6-copy">Сначала сохрани героя в аккаунт в разделе «Персонажи».</p><button className="w6-button" disabled={busy||!characterId||lobby.value.status==='closed'}>Добавить героя в кампанию</button></form></div>
 <div><h3>Чат кампании</h3><RemoteStatus error={messages.error} loading={messages.loading}/>{messages.value?.hasMore&&<button className="w6-button" onClick={()=>setBefore(messages.value!.items[0].created_at+'|'+messages.value!.items[0].id)}>Более ранние сообщения</button>}{before&&<button className="w6-button" onClick={()=>setBefore('')}>Последние сообщения</button>}<div className="w6-chat-feed" role="log" aria-label="Сообщения кампании">{messages.value?.items.map(p=><article className="w6-chat-message" key={p.id}><small>{p.author} · {formatDate(p.created_at)}</small><p className="w6-prose">{p.body}</p></article>)}</div><form className="w6-form" onSubmit={e=>{e.preventDefault();void act(async()=>{await request('/lobbies/'+opened+'/messages',{method:'POST',body:JSON.stringify({body:chat})});setChat('');setBefore('');return 'Сообщение отправлено участникам.'})}}><label className="w6-field"><span>Сообщение в кампанию</span><textarea required maxLength={4000} rows={3} value={chat} onChange={e=>setChat(e.currentTarget.value)}/></label><button className="w6-button w6-primary" disabled={busy||!chat.trim()||lobby.value.status==='closed'}>Отправить в чат</button></form><p className="w6-copy">Время мира: {state.value?.campaign.seconds??0} с. Действия и результаты подтверждает мастер.</p></div></div>
 {lobby.value.myRole==='GM'&&<div className="w6-fieldset"><h3>Общий редактор мастера</h3><p className="w6-copy">Редактор работает с полной анатомией и механикой этой кампании. Игрокам сервер выдаёт доступные им сведения.</p><button className="w6-button" disabled={busy} onClick={()=>{if(editor&&!window.confirm('Загрузить свежую кампанию? Текущий черновик редактора будет заменён.'))return;void act(loadEditor)}}>{editor?'Загрузить свежую кампанию':'Открыть кампанию в редакторе'}</button>{editor&&<><p className={editor.revision!==state.value?.revision?'w6-notice':'w6-copy'}>{editor.revision!==state.value?.revision?'На сервере появилась новая версия. Перед публикацией обнови черновик или разреши конфликт.':'Черновик использует текущую версию кампании.'}</p><Suspense fallback={<p>Загружаем редактор…</p>}><CharacterManager key={editorKey} initialWorld={editor} onRemotePublish={async value=>{const result=await request<{revision:number}>('/lobbies/'+opened+'/world',{method:'PUT',body:JSON.stringify({world:value,revision:editor.revision})});setEditor({...value,revision:result.revision});refresh();return 'Изменения кампании опубликованы участникам.'}}/></Suspense></>}</div>}
 </>}</section>}
 <p className="w6-notice" role="status">{message}</p></CommunityShell>
}
