import { useState } from 'react'
type Page='news'|'forum'|'support'|'stories'|'lobbies'
type Entry={id:string;title:string;text:string;at:string;replies:string[];genre:string;slots:number;energy:string;rank:string;selected:boolean}
const stories=[{title:'Лес, который помнит',text:'На границе поселения Аэлири деревья повторяют голоса пропавших. Найдите источник отголосков, не разрушив живую рощу.',hooks:'Пропавший проводник · След чужого контракта · Выбор между правдой и покоем'}, {title:'Долг подземной кузницы',text:'Кузница Каргаров получила артефакт, который не может держать ни один местный мастер. Кто доставил его и почему металл продолжает нагреваться?',hooks:'Опасная несовместимость · Потерянное клеймо · Цена изготовления'}, {title:'Тишина на переправе',text:'В нескольких домах исчезли звуки. Дорога к соседнему миру стала короче на одну ночь. Выясните, кто оставил теневой след.',hooks:'Магическое безмолвие · Странный переход · Ненадёжный свидетель'}]
function load(key:string):Entry[]{try{const raw=localStorage.getItem(key);if(!raw||raw.length>1e6)return [];const v=JSON.parse(raw);if(!Array.isArray(v)||v.length>100)return [];return v.filter(e=>e&&typeof e.id==='string'&&typeof e.title==='string'&&e.title.length<=120&&typeof e.text==='string'&&e.text.length<=2000&&typeof e.at==='string'&&Array.isArray(e.replies)&&e.replies.length<=50&&e.replies.every((r:unknown)=>typeof r==='string'&&r.length<=2000)&&typeof e.genre==='string'&&Number.isInteger(e.slots)&&e.slots>=1&&e.slots<=12&&['any','mana','shadow'].includes(e.energy)&&typeof e.rank==='string'&&typeof e.selected==='boolean')}catch{return []}}
export default function PortalSection({page,onCharacter}:{page:Page;onCharacter:()=>void}){
const key='world6.portal.'+page+'.v1', [entries,setEntries]=useState(()=>load(key)),[query,setQuery]=useState(''),[title,setTitle]=useState(''),[text,setText]=useState(''),[message,setMessage]=useState(''),[genre,setGenre]=useState('Приключение'),[slots,setSlots]=useState(4),[energy,setEnergy]=useState('any'),[rank,setRank]=useState('Элементалист'),[opened,setOpened]=useState(''),[reply,setReply]=useState('')
function save(next:Entry[]){try{localStorage.setItem(key,JSON.stringify(next));setEntries(next);setMessage('Сохранено в этом браузере.')}catch{setMessage('Не удалось сохранить: хранилище недоступно или заполнено.')}}
function create(){if(entries.length>=100){setMessage('Достигнут предел 100 записей.');return}if(!title.trim()||!text.trim())return;save([{id:crypto.randomUUID(),title:title.trim(),text:text.trim(),at:new Date().toISOString(),replies:[],genre,slots,energy,rank,selected:false},...entries]);setTitle('');setText('')}
function download(value:string,filename:string){const url=URL.createObjectURL(new Blob([value],{type:'text/plain;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=filename;link.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}
const names={news:'Новости мира',forum:'Форум',support:'Поддержка',stories:'Сюжеты',lobbies:'Поиск лобби'}
return <section className="panel w6-portal-page"><p className="w6-eyebrow">Сообщество Мира 6</p><h1>{names[page]}</h1>
{page==='news'&&<><article className="w6-news-feature"><small>РАЗРАБОТКА / РЕДАКТОР ПЕРСОНАЖА</small><h2>Тело, энергия и мастерство</h2><p>24 атрибута, ранги со ступенями, расы и формы, расчёт навыков и строгий выбор Маны или Тени.</p><button className="w6-button w6-primary" onClick={onCharacter}>Открыть редактор</button></article><div className="w6-race-cards"><article className="w6-race-card"><small>ПРАВИЛА</small><h3>Состояние вместо общего HP</h3><p>Локальные повреждения, диагностика, функциональные эффекты и отдельные игровые действия.</p></article><article className="w6-race-card"><small>ВИЗУАЛ</small><h3>Редактор внешности</h3><p>Вращаемое 3D тело и процедурные формы предметов.</p></article><article className="w6-race-card"><small>СЛЕДУЮЩИЙ ЭТАП</small><h3>Общая игра</h3><p>Для аккаунтов, общего форума и сетевого поиска лобби нужен сервер. Текущие разделы сохраняют данные локально.</p></article></div></>}
{page==='stories'&&<><p className="w6-copy">Авторские зацепки для кампаний, не новые утверждения о каноне.</p><div className="w6-story-grid">{stories.map((s,i)=><article className="w6-story-card" key={s.title}><span className="w6-card-number">0{i+1} / ПРИКЛЮЧЕНИЕ</span><h2>{s.title}</h2><p>{s.text}</p><details><summary>Зацепки</summary><p>{s.hooks}</p></details><button className="w6-button" onClick={()=>download(s.title+'\n'+s.text+'\n'+s.hooks,'world6-story.txt')}>Скачать сюжет</button></article>)}</div></>}
{(['forum','support','lobbies'] as Page[]).includes(page)&&<><p className="w6-copy">{page==='support'?'Обращение сохраняется как черновик. Отправка команде поддержки появится после подключения сервера.':page==='forum'?'Темы и ответы хранятся в этом браузере. Общие обсуждения между игроками требуют сервера.':'Локальные лобби для подготовки кампании. Сетевой поиск и приглашение игроков требуют сервера.'}</p><label className="w6-field"><span>Поиск по названию и описанию</span><input value={query} maxLength={120} onChange={e=>setQuery(e.currentTarget.value)}/></label><details className="w6-fieldset" open={page==='support'}><summary>{page==='forum'?'Создать тему':page==='support'?'Новое обращение':'Создать лобби'}</summary><form className="w6-form" onSubmit={e=>{e.preventDefault();create()}}><label className="w6-field"><span>Название</span><input required maxLength={120} value={title} onChange={e=>setTitle(e.currentTarget.value)}/></label><label className="w6-field"><span>{page==='support'?'Что произошло и как повторить':'Описание'}</span><textarea required rows={4} maxLength={2000} value={text} onChange={e=>setText(e.currentTarget.value)}/></label>{page==='lobbies'&&<div className="w6-attribute-grid"><label className="w6-field"><span>Жанр</span><select value={genre} onChange={e=>setGenre(e.currentTarget.value)}>{['Приключение','Исследование','Тайна','Свободная игра'].map(g=><option key={g}>{g}</option>)}</select></label><label className="w6-field"><span>Количество мест</span><input type="number" min={1} max={12} value={slots} onChange={e=>setSlots(Math.max(1,Math.min(12,Number(e.currentTarget.value))))}/></label><label className="w6-field"><span>Допустимая энергия</span><select value={energy} onChange={e=>setEnergy(e.currentTarget.value)}><option value="any">Любая из двух</option><option value="mana">Только Мана</option><option value="shadow">Только Тень</option></select></label><label className="w6-field"><span>Стартовый ранг</span><select value={rank} onChange={e=>setRank(e.currentTarget.value)}>{['Смертный','Заклинатель','Элементалист','Небесный лорд','Небесный монарх'].map(r=><option key={r}>{r}</option>)}</select></label></div>}<button className="w6-button w6-primary" type="submit">{page==='support'?'Сохранить черновик':'Создать'}</button></form></details>
<div className={page==='lobbies'?'w6-race-cards':''}>{entries.filter(t=>(t.title+' '+t.text+' '+t.genre).toLowerCase().includes(query.toLowerCase())).map(t=><article className="w6-race-card" key={t.id}><small>{page==='support'?'ЧЕРНОВИК · НЕ ОТПРАВЛЕН':page==='forum'?'ЛОКАЛЬНАЯ ТЕМА':t.genre+' · '+t.slots+' мест'}</small><h3>{t.title}</h3><p className="w6-prose">{t.text}</p>{page==='lobbies'&&<><p>{t.rank} · {t.energy==='any'?'Мана или Тень':t.energy==='mana'?'Мана':'Тень'}</p><button className="w6-button" onClick={()=>save(entries.map(x=>x.id===t.id?{...x,selected:!x.selected}:x))}>{t.selected?'Убрать из выбранных':'Выбрать лобби'}</button><button className="w6-button" onClick={onCharacter}>Подготовить героя</button></>}{page==='forum'&&<><button className="w6-button" onClick={()=>{setOpened(opened===t.id?'':t.id);setReply('')}}>Ответы · {t.replies.length}</button>{opened===t.id&&<><div>{t.replies.map((r,i)=><p className="w6-forum-reply w6-prose" key={i}>{r}</p>)}</div><form onSubmit={e=>{e.preventDefault();if(!reply.trim()||t.replies.length>=50)return;save(entries.map(x=>x.id===t.id?{...x,replies:[...x.replies,reply.trim()]}:x));setReply('')}}><label className="w6-field"><span>Ответ</span><textarea required maxLength={2000} value={reply} onChange={e=>setReply(e.currentTarget.value)}/></label><button className="w6-button" type="submit">Добавить ответ</button></form></>}</>}{page==='support'&&<button className="w6-button" onClick={()=>download(t.title+'\n\n'+t.text,'world6-support.txt')}>Скачать обращение</button>}<button className="w6-button w6-danger" onClick={()=>{if(window.confirm('Удалить эту локальную запись?'))save(entries.filter(x=>x.id!==t.id))}}>Удалить</button></article>)}</div>{!entries.length&&<div className="w6-empty"><h3>{page==='lobbies'?'Первая история ещё не началась':page==='forum'?'Место для первых идей':'Обращений пока нет'}</h3><p>Добавь первую запись с помощью формы выше.</p></div>}</>}
<p className="w6-notice" role="status">{message}</p></section>
}
