import { useState } from 'react'
import { useOnline } from './onlineContext'
import { useRemote } from './onlineHooks'
import type { Feed,Publication } from './onlineTypes'
import { CommunityShell,RemoteStatus,formatDate } from './NetworkCommon'
import { TextField } from './RpgControls'
export default function PublicationsPanel({kind}:{kind:'news'|'stories'}){
 const {user,request,refresh}=useOnline(),[offset,setOffset]=useState(0),[title,setTitle]=useState(''),[body,setBody]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),feed=useRemote<Feed<Publication>>('/publications/'+kind+'?offset='+offset)
 const moderator=!!user&&['ADMIN','OWNER'].includes(user.role),canPublish=kind==='stories'?!!user:moderator
 async function act(fn:()=>Promise<void>){setBusy(true);try{await fn();refresh();setMessage('Изменение опубликовано.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <CommunityShell title={kind==='news'?'Новости мира':'Сюжеты'}><p className="w6-copy">{kind==='stories'?'Авторские сюжеты участников. Публикация не добавляет новые правила в канон автоматически.':'Объявления и обновления от команды Мира 6.'}</p>{canPublish&&<details className="w6-fieldset"><summary>{kind==='news'?'Опубликовать новость':'Предложить сюжет'}</summary><form className="w6-form" onSubmit={e=>{e.preventDefault();void act(async()=>{await request('/publications/'+kind,{method:'POST',body:JSON.stringify({title,body})});setTitle('');setBody('')})}}><TextField label="Название публикации" value={title} onChange={setTitle}/><label className="w6-field"><span>Текст публикации</span><textarea required rows={6} maxLength={20000} value={body} onChange={e=>setBody(e.currentTarget.value)}/></label><button className="w6-button w6-primary" disabled={busy||!title.trim()||!body.trim()}>Опубликовать</button></form></details>}
 <RemoteStatus error={feed.error} loading={feed.loading}/><div className="w6-story-grid">{feed.value?.items.map(p=><article className="w6-story-card" key={p.id}><small>{p.author} · {formatDate(p.created_at)}</small><h2>{p.title}</h2><p className="w6-prose">{p.body}</p>{(moderator||kind==='stories'&&user?.id===p.author_id)&&<button className="w6-button w6-danger" disabled={busy} onClick={()=>{if(window.confirm('Удалить публикацию?'))void act(async()=>{await request('/publications/'+kind+'/'+p.id,{method:'DELETE'})})}}>Удалить публикацию</button>}</article>)}</div>{feed.value?.items.length===0&&<p>Публикаций пока нет.</p>}<div className="w6-buttons">{offset>0&&<button className="w6-button" onClick={()=>setOffset(offset-20)}>Предыдущие публикации</button>}{feed.value?.hasMore&&<button className="w6-button" onClick={()=>setOffset(offset+20)}>Следующие публикации</button>}</div>
 {kind==='stories'&&<details className="w6-fieldset"><summary>Стартовые зацепки для кампании</summary>{[['Лес, который помнит','На границе поселения Аэлири деревья повторяют голоса пропавших. Найдите источник отголосков, не разрушив живую рощу.'],['Долг подземной кузницы','Кузница Каргаров получила артефакт, который не может держать ни один местный мастер. Кто доставил его и почему металл продолжает нагреваться?'],['Тишина на переправе','В нескольких домах исчезли звуки. Дорога к соседнему миру стала короче на одну ночь. Выясните, кто оставил теневой след.']].map(([title,text])=><article className="w6-entry" key={title}><h3>{title}</h3><p>{text}</p></article>)}</details>}
 <p className="w6-notice" role="status">{message}</p></CommunityShell>
}
