import { skillCatalog } from './creationRules'
import { stateById } from './functionalStates'
import { isArtwork } from './visualMedia'
import { isSceneState, copySceneState } from './scenes'
import { copyHitLocation, isHitLocation, isDetailedAnatomy, copyDetailedAnatomy } from './anatomyModel'
import { schoolById } from './magicCatalog'
import { statisticFields } from './characterStatistics'
import { isBodyPart, cloneBody } from './characterBody'
import type { AbilityDefinition, AbilityTemplate, Campaign, Formula, InventoryItem, ItemDefinition, ItemTemplate, LearnedAbility, Modifier, Physiology, RpgState } from './rpgTypes'
export const parameterFields = [...statisticFields.map(f => ({ key: f.key, label: f.label })),
  { key: 'maximumMana', label: 'Максимум Маны' },
  { key: 'maximumShadow', label: 'Максимум Тени' }, { key: 'maximumStamina', label: 'Максимум Выносливости' }] as const
import { attrKeys, legacyAttributeKeys } from './attributes'
export { attrKeys } from './attributes'
export const obj = (v: unknown): v is Record<string, unknown> => typeof v === 'object' && v !== null && !Array.isArray(v)
export const num = (v: unknown): v is number => typeof v === 'number' && Number.isFinite(v) && Math.abs(v) <= 1e12
const nonneg = (v: unknown): v is number => num(v) && v >= 0
const text = (v: unknown, max = 4000): v is string => typeof v === 'string' && v.length <= max
const id = (v: unknown): v is string => text(v,160) && /^[a-zA-Z0-9:_-]+$/.test(v)
const arr = (v: unknown, fn: (v: unknown) => boolean, max = 200): v is unknown[] => Array.isArray(v) && v.length <= max && v.every(fn)
const tags = (v: unknown) => arr(v, t => text(t,120) && !!t.trim(),100)
const one = (v: unknown, list: readonly string[]) => typeof v === 'string' && list.includes(v)
const unique = (v: unknown[], key = 'id') => new Set(v.map(x => (x as Record<string, unknown>)[key])).size === v.length
export const isCost = (v: unknown) => obj(v) && ['mana','shadow','stamina'].every(k => nonneg(v[k]))
export const isModifier = (v: unknown): v is Modifier => obj(v) && (v.parameter==='maximumHealth'||parameterFields.some(f => f.key === v.parameter)) && num(v.flat) && num(v.percent)
export const isFormula = (v: unknown): v is Formula => obj(v) && (v.parameter==='maximumHealth'||parameterFields.some(f => f.key === v.parameter)) && one(v.mode,['manual','formula','adjusted']) && num(v.base) && num(v.adjustment) && obj(v.weights) && Object.keys(v.weights).every(k=>attrKeys.includes(k as typeof attrKeys[number])) && attrKeys.every(k=>(v.weights as Record<string,unknown>)[k] === undefined && !legacyAttributeKeys.some(x=>x===k) || num((v.weights as Record<string,unknown>)[k]))
export function isItem(v: unknown): v is ItemDefinition {
  return obj(v) && ['modelLength','modelWidth','modelDepth'].every(k=>v[k]===undefined||nonneg(v[k])&&(v[k] as number)>=.1&&(v[k] as number)<=3) && (v.artifactCharge===undefined||nonneg(v.artifactCharge)&&v.artifactCharge<=(v.energyReserve as number??0)) && (v.activationCost===undefined||nonneg(v.activationCost)) && (v.activationDuration===undefined||nonneg(v.activationDuration)) && (v.activationModifiers===undefined||arr(v.activationModifiers,isModifier,50)) && (v.artifactLevel===undefined||nonneg(v.artifactLevel)&&Number.isInteger(v.artifactLevel)&&v.artifactLevel<=12) && (v.minimumLevel===undefined||nonneg(v.minimumLevel)&&v.minimumLevel<=49) && (v.energyReserve===undefined||nonneg(v.energyReserve)) && (v.energyType===undefined||one(v.energyType,['mana','shadow'])) && (v.effectDescription===undefined||text(v.effectDescription)) && (v.category===undefined||one(v.category,['weapon','armor','focus','jewelry','tool','consumable'])) && (v.shape===undefined||one(v.shape,['sword','staff','ring','shield','orb','dagger','axe','bow','amulet','helmet','armor','potion'])) && (v.color===undefined||typeof v.color==='string'&&/^#[\da-f]{6}$/i.test(v.color)) && (v.artwork===undefined||isArtwork(v.artwork)) && text(v.name,120) && !!v.name.trim() && text(v.description) && nonneg(v.massKg) && text(v.material,120) && nonneg(v.thicknessMm) && tags(v.tags) && one(v.slot,['none','left','right','both','body']) && nonneg(v.layer) && Number.isInteger(v.layer) && tags(v.covers) && tags(v.conflictTags) && tags(v.compatibleTags) && nonneg(v.maximumDurability) && nonneg(v.absorptionJ) && nonneg(v.transmission) && v.transmission <= 1 && nonneg(v.joulesPerWear) && arr(v.modifiers,isModifier,50) && typeof v.worksBroken === 'boolean'
}
export const isItemTemplate = (v: unknown): v is ItemTemplate => obj(v) && isItem(v) && id((v as ItemTemplate).id)
export function isInventoryItem(v: unknown): v is InventoryItem {
  if (!obj(v) || !isItemTemplate(v)) return false
  const x=v as InventoryItem
  return text(x.templateId,160) && nonneg(x.quantity) && Number.isInteger(x.quantity) && x.quantity > 0 && nonneg(x.durability) && x.durability <= x.maximumDurability && typeof x.equipped === 'boolean' && (!x.equipped || x.quantity === 1 && x.slot !== 'none')
}
export function isAbility(v: unknown): v is AbilityDefinition {
  return obj(v) && (v.basisSchoolId===undefined||typeof v.basisSchoolId==='string'&&!!schoolById(v.basisSchoolId)&&schoolById(v.basisSchoolId)?.group!=='extended'&&v.basisSchoolId!=='limit') && (v.skillId===undefined||skillCatalog.some(s=>s.id===v.skillId)) && (v.minimumLevel===undefined||nonneg(v.minimumLevel)&&v.minimumLevel<=49) && (v.mastery===undefined||nonneg(v.mastery)&&v.mastery<=100) && (v.innate===undefined||typeof v.innate==='boolean') && (v.raceId===undefined||text(v.raceId,120)) && (v.statusEffects===undefined||arr(v.statusEffects,id=>typeof id==='string'&&!!stateById(id),24)) && (v.attributeRequirements===undefined||obj(v.attributeRequirements)&&Object.entries(v.attributeRequirements).every(([k,n])=>attrKeys.includes(k as typeof attrKeys[number])&&nonneg(n))) && (v.flight===undefined||typeof v.flight==='boolean') && (v.requiredStructures===undefined||tags(v.requiredStructures)) && (v.artwork===undefined||isArtwork(v.artwork)) && (v.damageType===undefined||one(v.damageType,['blunt','pierce','cut'])) && (v.schoolId===undefined||v.schoolId===''||typeof v.schoolId==='string'&&!!schoolById(v.schoolId)) && text(v.name,120) && !!v.name.trim() && text(v.description) && nonneg(v.strength) && one(v.mechanism,['stone','impact','manual','heal','blood','substitute','effect']) && isCost(v.cost) && isCost(v.upkeep) && ['preparation','duration','rangeM','massKg','speedMs','contactCm2','healAmount','bloodMlPerSecond','substituteMl'].every(k=>nonneg(v[k])) && typeof v.requiresAwake === 'boolean' && one(v.hands,['none','any','left','right','both']) && ['freeHands','movement','speech','stopBleeding'].every(k=>typeof v[k]==='boolean') && tags(v.requiredTags) && tags(v.requiredParts) && tags(v.cureLabels) && text(v.condition,1000) && arr(v.modifiers,isModifier,50) && text(v.stackKey,120) && one(v.stacking,['strongest','add','refresh']) && (!['stone','impact'].includes(String(v.mechanism)) || (v.massKg as number) > 0 && (v.speedMs as number) > 0 && (v.contactCm2 as number) > 0)
}
export const isAbilityTemplate = (v: unknown): v is AbilityTemplate => obj(v) && isAbility(v) && id((v as AbilityTemplate).id)
export const isLearnedAbility = (v: unknown): v is LearnedAbility => obj(v) && isAbilityTemplate(v) && text((v as LearnedAbility).templateId,160) && typeof (v as LearnedAbility).approved === 'boolean'
export const isPhysiology = (v: unknown): v is Physiology => obj(v) && ['weakModifiers','impairedModifiers','criticalModifiers'].every(k=>arr(v[k],m=>isModifier(m) && !m.parameter.startsWith('maximum'),50)) && text(v.race,120) && one(v.mode,['blood','mana','shadow','none']) && ['normalMl','currentMl','totalLostMl','naturalMlPerSecond','weakFraction','impairedFraction','criticalFraction'].every(k=>nonneg(v[k])) && (v.currentMl as number) <= (v.normalMl as number) && (v.weakFraction as number) < (v.impairedFraction as number) && (v.impairedFraction as number) < (v.criticalFraction as number) && (v.criticalFraction as number) <= 1
const log = (v: unknown) => obj(v) && id(v.id) && nonneg(v.seconds) && text(v.text,4000) && text(v.details,12000)
const input = (v: unknown) => obj(v) && (v.hit===undefined||isHitLocation(v.hit)) && (v.skipAnatomy===undefined||typeof v.skipAnatomy==='boolean') && (v.structureId===undefined||v.structureId===''||id(v.structureId)) && text(v.region,160) && ['distanceM','manualLocal','manualSystemic','bleedingMlPerSecond','criticalContactFactor'].every(k=>nonneg(v[k])) && nonneg(v.criticalChance) && v.criticalChance <= 100 && nonneg(v.dodgeChance) && v.dodgeChance <= 100 && ['accessible','conditionsConfirmed','canSpeak','gapConfirmed'].every(k=>typeof v[k]==='boolean') && one(v.armorPath,['covered','gap']) && text(v.injury,120) && text(v.note,1000)
const effect = (v: unknown) => obj(v) && (v.statusEffects===undefined||arr(v.statusEffects,id=>typeof id==='string'&&!!stateById(id),24)) && id(v.id) && nonneg(v.strength) && text(v.name,120) && text(v.stackKey,120) && one(v.stacking,['strongest','add','refresh']) && arr(v.modifiers,isModifier,50) && (v.expiresAt === null || nonneg(v.expiresAt)) && nonneg(v.bloodMlPerSecond) && nonneg(v.substituteMl) && text(v.ownerId,160) && text(v.castId,160)
const cast = (v: unknown) => obj(v) && id(v.id) && isLearnedAbility(v.ability) && text(v.targetId,160) && input(v.input) && one(v.status,['preparing','ready','maintaining','ended','interrupted']) && nonneg(v.readyAt) && (v.endsAt === null || nonneg(v.endsAt))
export function isRpg(v: unknown): v is RpgState {
  if (!obj(v) || !arr(v.inventory,isInventoryItem) || !arr(v.abilities,isLearnedAbility) || !arr(v.formulas,isFormula,80) || !arr(v.effects,effect) || !arr(v.casts,cast) || !arr(v.logs,log) || !isPhysiology(v.physiology) || !obj(v.impact) || typeof v.dead !== 'boolean') return false
  return [v.inventory,v.abilities,v.effects,v.casts,v.logs].every(a=>unique(a as unknown[])) && unique(v.formulas,'parameter') && Object.keys(v.impact).length <= 64 && Object.entries(v.impact).every(([k,x]) => id(k) && obj(x) && nonneg(x.thresholdJ) && num(x.joulesPerHp) && x.joulesPerHp > 0 && num(x.referenceCm2) && x.referenceCm2 > 0)
}
export function isCampaign(v: unknown): v is Campaign {
  return obj(v) && (v.scenes === undefined || isSceneState(v.scenes)) && nonneg(v.seconds) && nonneg(v.revision) && Number.isInteger(v.revision) && arr(v.items,isItemTemplate) && arr(v.abilities,isAbilityTemplate) && arr(v.logs,log) && arr(v.anatomies,x=>obj(x) && id(x.id) && text(x.name,120) && !!x.name.trim() && obj(x.parts) && (x.physiology===undefined||isPhysiology(x.physiology)) && (x.anatomy===undefined||isDetailedAnatomy(x.anatomy,Object.keys(x.parts))) && Object.keys(x.parts).length <= 64 && Object.keys(x.parts).length > 0 && Object.entries(x.parts).every(([k,p])=>id(k) && isBodyPart(p)),50) && [v.items,v.abilities,v.logs,v.anatomies].every(a=>unique(a as unknown[]))
}
export const emptyCost = () => ({mana:0,shadow:0,stamina:0})
export const emptyPhysiology = (): Physiology => ({weakModifiers:[],impairedModifiers:[],criticalModifiers:[],race:'',mode:'blood',normalMl:0,currentMl:0,totalLostMl:0,naturalMlPerSecond:0,weakFraction:0.15,impairedFraction:0.3,criticalFraction:0.4})
export const emptyRpg = (): RpgState => ({inventory:[],abilities:[],formulas:[],effects:[],physiology:emptyPhysiology(),impact:{},casts:[],logs:[],dead:false})
export const emptyCampaign = (): Campaign => ({seconds:0,revision:0,items:[],abilities:[],anatomies:[],logs:[]})
export const emptyItem = (): ItemDefinition => ({name:'',description:'',massKg:0,material:'',thicknessMm:0,tags:[],slot:'none',layer:0,covers:[],conflictTags:[],compatibleTags:[],maximumDurability:100,absorptionJ:0,transmission:1,joulesPerWear:0,modifiers:[],worksBroken:false})
export const emptyAbility = (): AbilityDefinition => ({schoolId:'',strength:1,name:'',description:'',mechanism:'manual',cost:emptyCost(),upkeep:emptyCost(),preparation:0,duration:0,rangeM:0,requiresAwake:true,hands:'none',freeHands:false,movement:false,speech:false,requiredParts:[],requiredTags:[],condition:'',massKg:1,speedMs:10,contactCm2:10,healAmount:0,stopBleeding:false,cureLabels:[],bloodMlPerSecond:0,substituteMl:0,modifiers:[],stackKey:'',stacking:'strongest'})
// Явный список известных полей: JSON-обмен не переносит неизвестные/тайные свойства.
export function copyItem(v: ItemDefinition): ItemDefinition { return {...(v.activationModifiers?{activationModifiers:v.activationModifiers.map(copyModifier)}:{}),...Object.fromEntries(['artifactCharge','activationCost','activationDuration','artifactLevel','minimumLevel','energyType','energyReserve','effectDescription','category','shape','color','modelLength','modelWidth','modelDepth'].filter(k=>(v as unknown as Record<string,unknown>)[k]!==undefined).map(k=>[k,(v as unknown as Record<string,unknown>)[k]])),...(v.artwork!==undefined?{artwork:v.artwork}:{}),name:v.name,description:v.description,massKg:v.massKg,material:v.material,thicknessMm:v.thicknessMm,tags:[...v.tags],slot:v.slot,layer:v.layer,covers:[...v.covers],conflictTags:[...v.conflictTags],compatibleTags:[...v.compatibleTags],maximumDurability:v.maximumDurability,absorptionJ:v.absorptionJ,transmission:v.transmission,joulesPerWear:v.joulesPerWear,modifiers:v.modifiers.map(copyModifier),worksBroken:v.worksBroken} }
const copyModifier = (m: Modifier): Modifier => ({parameter:m.parameter,flat:m.flat,percent:m.percent})
export function copyAbility(v: AbilityDefinition): AbilityDefinition { return {...(v.basisSchoolId?{basisSchoolId:v.basisSchoolId}:{}),...(v.skillId?{skillId:v.skillId}:{}),...(v.minimumLevel!==undefined?{minimumLevel:v.minimumLevel}:{}),...(v.mastery!==undefined?{mastery:v.mastery}:{}),...(v.innate!==undefined?{innate:v.innate}:{}),...(v.raceId!==undefined?{raceId:v.raceId}:{}),...(v.attributeRequirements?{attributeRequirements:{...v.attributeRequirements}}:{}),...(v.statusEffects?{statusEffects:[...v.statusEffects]}:{}),...(v.flight!==undefined?{flight:v.flight}:{}),...(v.requiredStructures!==undefined?{requiredStructures:[...v.requiredStructures]}:{}),...(v.artwork!==undefined?{artwork:v.artwork}:{}),...(v.damageType!==undefined?{damageType:v.damageType}:{}),...(v.schoolId!==undefined?{schoolId:v.schoolId}:{}),strength:v.strength,name:v.name,description:v.description,mechanism:v.mechanism,cost:{mana:v.cost.mana,shadow:v.cost.shadow,stamina:v.cost.stamina},upkeep:{mana:v.upkeep.mana,shadow:v.upkeep.shadow,stamina:v.upkeep.stamina},preparation:v.preparation,duration:v.duration,rangeM:v.rangeM,requiresAwake:v.requiresAwake,hands:v.hands,freeHands:v.freeHands,movement:v.movement,speech:v.speech,requiredParts:[...v.requiredParts],requiredTags:[...v.requiredTags],condition:v.condition,massKg:v.massKg,speedMs:v.speedMs,contactCm2:v.contactCm2,healAmount:v.healAmount,stopBleeding:v.stopBleeding,cureLabels:[...v.cureLabels],bloodMlPerSecond:v.bloodMlPerSecond,substituteMl:v.substituteMl,modifiers:v.modifiers.map(copyModifier),stackKey:v.stackKey,stacking:v.stacking} }
export function copyRpg(v?: RpgState): RpgState {
  const x=v??emptyRpg()
  const inputCopy = (i: RpgState['casts'][number]['input']) => ({...(i.structureId!==undefined?{structureId:i.structureId}:{}),...(i.skipAnatomy!==undefined?{skipAnatomy:i.skipAnatomy}:{}),...(i.hit?{hit:copyHitLocation(i.hit)}:{}),region:i.region,distanceM:i.distanceM,accessible:i.accessible,conditionsConfirmed:i.conditionsConfirmed,canSpeak:i.canSpeak,armorPath:i.armorPath,gapConfirmed:i.gapConfirmed,criticalChance:i.criticalChance,dodgeChance:i.dodgeChance,criticalContactFactor:i.criticalContactFactor,manualLocal:i.manualLocal,manualSystemic:i.manualSystemic,bleedingMlPerSecond:i.bleedingMlPerSecond,injury:i.injury,note:i.note})
  return {inventory:x.inventory.map(i=>({...copyItem(i),id:i.id,templateId:i.templateId,quantity:i.quantity,durability:i.durability,equipped:i.equipped})),abilities:x.abilities.map(a=>({...copyAbility(a),id:a.id,templateId:a.templateId,approved:a.approved})),formulas:x.formulas.map(f=>({parameter:f.parameter,mode:f.mode,base:f.base,weights:Object.fromEntries(attrKeys.map(k=>[k,f.weights[k]??0])) as Formula['weights'],adjustment:f.adjustment})),effects:x.effects.map(e=>({...(e.statusEffects?{statusEffects:[...e.statusEffects]}:{}),id:e.id,strength:e.strength,name:e.name,stackKey:e.stackKey,stacking:e.stacking,modifiers:e.modifiers.map(copyModifier),expiresAt:e.expiresAt,bloodMlPerSecond:e.bloodMlPerSecond,substituteMl:e.substituteMl,ownerId:e.ownerId,castId:e.castId})),physiology:{weakModifiers:x.physiology.weakModifiers.map(copyModifier),impairedModifiers:x.physiology.impairedModifiers.map(copyModifier),criticalModifiers:x.physiology.criticalModifiers.map(copyModifier),race:x.physiology.race,mode:x.physiology.mode,normalMl:x.physiology.normalMl,currentMl:x.physiology.currentMl,totalLostMl:x.physiology.totalLostMl,naturalMlPerSecond:x.physiology.naturalMlPerSecond,weakFraction:x.physiology.weakFraction,impairedFraction:x.physiology.impairedFraction,criticalFraction:x.physiology.criticalFraction},impact:Object.fromEntries(Object.entries(x.impact).map(([k,p])=>[k,{thresholdJ:p.thresholdJ,joulesPerHp:p.joulesPerHp,referenceCm2:p.referenceCm2}])),casts:x.casts.map(c=>({id:c.id,ability:{...copyAbility(c.ability),id:c.ability.id,templateId:c.ability.templateId,approved:c.ability.approved},targetId:c.targetId,input:inputCopy(c.input),status:c.status,readyAt:c.readyAt,endsAt:c.endsAt})),logs:x.logs.map(l=>({id:l.id,seconds:l.seconds,text:l.text,details:l.details})),dead:x.dead}
}

export function copyCampaign(c:Campaign):Campaign{return {...(c.scenes?{scenes:copySceneState(c.scenes)}:{}),seconds:c.seconds,revision:c.revision,items:c.items.map(i=>({...copyItem(i),id:i.id})),abilities:c.abilities.map(a=>({...copyAbility(a),id:a.id})),anatomies:c.anatomies.map(a=>({id:a.id,name:a.name,...(a.anatomy?{anatomy:copyDetailedAnatomy(a.anatomy)}:{}),parts:cloneBody({parts:a.parts,consciousness:'awake',history:[]}).parts,...(a.physiology?{physiology:copyRpg({...emptyRpg(),physiology:a.physiology}).physiology}:{})})),logs:c.logs.map(l=>({id:l.id,seconds:l.seconds,text:l.text,details:l.details}))}}
