import { useState } from 'react'
import type { Actor } from './rpgEngine'
import { skillCatalog, skillChance, skillBreakdown } from './creationRules'
import type { SkillKey } from './creationRules'
import { bodyConsequences } from './characterBody'
export default function SkillCheckPanel({actor,seconds,onChange}:{actor:Actor;seconds:number;onChange:(a:Actor)=>void}){
 const [skill,setSkill]=useState<SkillKey>('stealth'),[difficulty,setDifficulty]=useState(30),[note,setNote]=useState(''),[message,setMessage]=useState('')
 const calculation=skillBreakdown(actor,skill,seconds),value=calculation.value,chance=skillChance(value,difficulty)
 function roll(){const c=bodyConsequences(actor.body);if(actor.rpg.dead||actor.body.consciousness!=='awake'){setMessage('Проверка требует живого персонажа в сознании.');return}if(['pickpocket','lockpicking','disarm','forging','crafting'].includes(skill)&&!c.leftHand&&!c.rightHand){setMessage('Для действия нужна хотя бы одна работающая рука.');return}if(skill==='stealth'&&c.movementFactor<=0){setMessage('Персонаж не может передвигаться скрытно.');return}const random=crypto.getRandomValues(new Uint32Array(1))[0]/4294967296*100,success=random<chance,text=skillCatalog.find(s=>s.id===skill)!.name+': '+(success?'успех':'неудача'),details=`Оценка ${value}; сложность ${difficulty}; шанс ${chance}%; бросок ${random.toFixed(2)}. ${note}`;onChange({...actor,rpg:{...actor.rpg,logs:[...actor.rpg.logs,{id:crypto.randomUUID(),seconds,text,details}].slice(-200)}});setMessage(text+' · '+details)}
 return <section className="w6-fieldset"><h3>Проверка навыка</h3><div className="w6-attribute-grid"><label className="w6-field"><span>Навык</span><select value={skill} onChange={e=>setSkill(e.currentTarget.value as SkillKey)}>{skillCatalog.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="w6-field"><span>Сложность с учётом сцены</span><input type="number" min={0} max={1000} value={difficulty} onChange={e=>setDifficulty(Math.max(0,Math.min(1000,Number(e.currentTarget.value))))}/></label><label className="w6-field"><span>Условия и обоснование мастера</span><input maxLength={1000} value={note} onChange={e=>setNote(e.currentTarget.value)}/></label></div><p>Оценка <strong>{value}</strong> · вероятность <strong>{chance}%</strong></p><details className="w6-fieldset"><summary>Как рассчитан навык и шанс</summary><ul>{calculation.terms.map(t=><li key={t.label}>{t.label}: {t.value} × {t.weight} = {Number((t.value*t.weight).toFixed(3))}</li>)}</ul><p>Взвешенные атрибуты: {Number(calculation.aptitude.toFixed(3))}. Освоение: {calculation.level}; обучение расы: ×{calculation.learning}.</p><p>Оценка = (({Number(calculation.aptitude.toFixed(3))} × 0,6 + {calculation.level} × 1,4 × {calculation.learning}) × {calculation.masteryFactor} + {calculation.flat}) × (1 + {calculation.percent} / 100) = {value}.</p><p>Шанс = 50 + 50 × (оценка − сложность) / (оценка + сложность + 20), в пределах 5–95%: {chance}%. Активные эффекты и боль учитываются; повторения одного эффекта используют правило сложения.</p></details><button className="w6-button w6-primary" onClick={roll}>Выполнить проверку и записать</button><p role="status" className="w6-notice">{message}</p></section>
}
