import { useState } from 'react'
import { useOnline } from './onlineContext'
import { useRemote } from './onlineHooks'
import type { Ticket,Post } from './onlineTypes'
import { CommunityShell,RemoteStatus,formatDate } from './NetworkCommon'
import { TextField } from './RpgControls'
export default function SupportPanel({onAccount}:{onAccount:()=>void}){
 const {user,request,refresh}=useOnline(),[opened,setOpened]=useState(''),[title,setTitle]=useState(''),[body,setBody]=useState(''),[reply,setReply]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),feed=useRemote<Ticket[]>(user?'/support':null),thread=useRemote<{ticket:Ticket;replies:Post[]}>(user&&opened?'/support/'+opened:null)
 const moderator=!!user&&['ADMIN','OWNER'].includes(user.role)
 async function act(fn:()=>Promise<void>){setBusy(true);try{await fn();refresh();setMessage('Обращение сохранено на сервере.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <CommunityShell title="Поддержка"><p className="w6-copy">Обращение доступно его автору и администраторам. Укажи, что произошло, как повторить ошибку и какой результат ожидался.</p>{!user?<button className="w6-button" onClick={onAccount}>Войти для обращения</button>:<><details className="w6-fieldset"><summary>Новое обращение</summary><form className="w6-form" onSubmit={e=>{e.preventDefault();void act(async()=>{const result=await request<{id:string}>('/support',{method:'POST',body:JSON.stringify({title,body})});setOpened(result.id);setTitle('');setBody('')})}}><TextField label="Тема обращения" value={title} onChange={setTitle}/><label className="w6-field"><span>Описание проблемы</span><textarea required rows={5} maxLength={8000} value={body} onChange={e=>setBody(e.currentTarget.value)}/></label><button className="w6-button w6-primary" disabled={busy||!title.trim()||!body.trim()}>Отправить обращение</button></form></details><button className="w6-button" onClick={refresh}>Обновить обращения</button><RemoteStatus error={feed.error} loading={feed.loading}/><div className="w6-topic-list">{feed.value?.map(t=><button className="w6-topic-row" key={t.id} onClick={()=>setOpened(t.id)}><span><strong>{t.title}</strong><small>{t.author} · {formatDate(t.updated_at)}</small></span><small>{t.status==='open'?'Новое':t.status==='working'?'В работе':'Закрыто'}</small></button>)}</div>
 <RemoteStatus error={thread.error} loading={thread.loading}/>{thread.value&&<div className="w6-thread"><h2>{thread.value.ticket.title}</h2><p className="w6-prose">{thread.value.ticket.body}</p>{thread.value.replies.map(p=><article className="w6-forum-post" key={p.id}><small>{p.author} · {formatDate(p.created_at)}</small><p className="w6-prose">{p.body}</p></article>)}{moderator&&<label className="w6-field"><span>Статус обращения</span><select aria-label="Статус обращения" value={thread.value.ticket.status} disabled={busy} onChange={e=>{const status=e.currentTarget.value;void act(async()=>{await request('/support/'+opened,{method:'PATCH',body:JSON.stringify({status})})})}}><option value="open">Новое</option><option value="working">В работе</option><option value="closed">Закрыто</option></select></label>}{thread.value.ticket.status!=='closed'&&<form className="w6-form" onSubmit={e=>{e.preventDefault();void act(async()=>{await request('/support/'+opened+'/replies',{method:'POST',body:JSON.stringify({body:reply})});setReply('')})}}><label className="w6-field"><span>Дополнение к обращению</span><textarea required maxLength={8000} rows={3} value={reply} onChange={e=>setReply(e.currentTarget.value)}/></label><button className="w6-button" disabled={busy||!reply.trim()}>Отправить ответ в поддержку</button></form>}</div>}</>}
 <p className="w6-notice" role="status">{message}</p></CommunityShell>
}
